# Generated by Django 3.2.11 on 2022-02-09 22:00

import datetime
from django.db import migrations, models
import fecfiler.custom_storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMaster',
            fields=[
                ('cmte_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('cmte_name', models.CharField(blank=True, max_length=200, null=True)),
                ('street_1', models.CharField(blank=True, max_length=34, null=True)),
                ('street_2', models.CharField(blank=True, max_length=34, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True)),
                ('cmte_email_1', models.CharField(blank=True, max_length=100, null=True)),
                ('cmte_email_2', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('cmte_type', models.CharField(blank=True, max_length=1, null=True)),
                ('cmte_dsgn', models.CharField(blank=True, max_length=1, null=True)),
                ('cmte_filing_freq', models.CharField(blank=True, max_length=1, null=True)),
                ('cmte_filed_type', models.CharField(blank=True, max_length=1, null=True)),
                ('treasurer_last_name', models.CharField(blank=True, max_length=90, null=True)),
                ('treasurer_first_name', models.CharField(blank=True, max_length=90, null=True)),
                ('treasurer_middle_name', models.CharField(blank=True, max_length=90, null=True)),
                ('treasurer_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('treasurer_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('last_update_date', models.TimeField()),
            ],
            options={
                'db_table': 'committee_lookup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefCmteTypeVsForms',
            fields=[
                ('cmte_type', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('cmte_dsgn', models.CharField(max_length=1)),
                ('form_type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=25)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_cmte_type_vs_forms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefFormsVsReports',
            fields=[
                ('form_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=10)),
                ('filing_freq', models.CharField(blank=True, max_length=1, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_forms_vs_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefFormTypes',
            fields=[
                ('form_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('form_description', models.CharField(blank=True, max_length=300, null=True)),
                ('form_tooltip', models.CharField(blank=True, max_length=1000, null=True)),
                ('form_pdf_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ref_form_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefRptTypes',
            fields=[
                ('rpt_type', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('rpt_type_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('rpt_type_order', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_rpt_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('committeeid', models.CharField(max_length=9)),
                ('committeename', models.CharField(max_length=200)),
                ('street1', models.CharField(max_length=34)),
                ('street2', models.CharField(max_length=34)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
                ('treasurerlastname', models.CharField(max_length=30)),
                ('treasurerfirstname', models.CharField(max_length=20)),
                ('treasurermiddlename', models.CharField(max_length=20)),
                ('treasurerprefix', models.CharField(max_length=10)),
                ('treasurersuffix', models.CharField(max_length=10)),
                ('email_on_file', models.TextField(default='-', max_length=100)),
                ('email_on_file_1', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committee',
            },
        ),
        migrations.CreateModel(
            name='CommitteeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('committeeid', models.CharField(max_length=9)),
                ('committeename', models.CharField(max_length=200)),
                ('street1', models.CharField(max_length=34)),
                ('street2', models.CharField(blank=True, max_length=34, null=True)),
                ('text', models.TextField(default='-', max_length=20000)),
                ('reason', models.CharField(default='-', max_length=3)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.TextField(max_length=9)),
                ('treasurerlastname', models.CharField(max_length=30)),
                ('treasurerfirstname', models.CharField(max_length=20)),
                ('treasurermiddlename', models.CharField(blank=True, max_length=20, null=True)),
                ('treasurerprefix', models.CharField(blank=True, max_length=10, null=True)),
                ('treasurersuffix', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('signee', models.CharField(default='-', max_length=30)),
                ('email_on_file', models.TextField(default='-', max_length=100)),
                ('email_on_file_1', models.TextField(blank=True, max_length=100, null=True)),
                ('additional_email_1', models.TextField(blank=True, max_length=100, null=True)),
                ('additional_email_2', models.TextField(blank=True, max_length=100, null=True)),
                ('filename', models.CharField(blank=True, max_length=128, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=fecfiler.custom_storages.MediaStorage(), upload_to='')),
                ('form_type', models.CharField(default='F99', max_length=3)),
                ('coverage_start_date', models.DateField(blank=True, null=True)),
                ('coverage_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CommitteeInfo',
                'verbose_name_plural': 'CommitteeInfo',
            },
        ),
        migrations.CreateModel(
            name='F99Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='My_Forms_View',
            fields=[
                ('cmte_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=25)),
                ('form_type', models.CharField(max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('form_description', models.CharField(blank=True, max_length=300, null=True)),
                ('form_info', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
