# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommitteeInfoModel',
            new_name='CommitteeInfo',
        ),
    ]
