# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20180918_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeeinfo',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='committeeinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='committeeinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
