# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20180918_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeinfo',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='committeeinfo',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
