# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20180918_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeinfo',
            name='text',
            field=models.TextField(default='-', max_length=20000),
        ),
    ]
