# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_committeeinfo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeinfo',
            name='committeeid',
            field=models.CharField(max_length=9),
        ),
        migrations.AddField(
            model_name='committeeinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
