# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_committeeinfo_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeinfo',
            name='zipcode',
            field=models.TextField(max_length=5),
        ),
    ]
