# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20180925_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeinfo',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
