# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_committeeinfo_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeinfo',
            name='reason',
            field=models.CharField(default='-', max_length=3),
        ),
    ]
