# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20181004_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeinfo',
            name='additional_email_1',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='committeeinfo',
            name='additional_email_2',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='committeeinfo',
            name='email_on_file',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='committeeinfo',
            name='signee',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
