# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20181017_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='email_on_file',
            field=models.TextField(default='-', max_length=100),
        ),
    ]
