# -*- coding: utf-8 -*-
#Generated by Django 1.11 on 2018-10-24 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import fecfiler.forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_committeeinfo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeinfo',
            name='file',
            field=models.FileField(null=True, upload_to='f99/', validators=[fecfiler.forms.validators.validate_is_pdf]),
        ),
        migrations.AlterField(
            model_name='committeeinfo',
            name='street2',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='committeeinfo',
            name='treasurermiddlename',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='committeeinfo',
            name='treasurerprefix',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='committeeinfo',
            name='treasurersuffix',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
~      
