# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20181030_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeinfo',
            name='file',
            field=models.BinaryField(null=True),
        ),
    ]
