# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_auto_20181030_1920'),
        ('forms', '0015_auto_20181024_1619'),
    ]

    operations = [
    ]
