# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import fecfiler.forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_merge_20181107_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeinfo',
            name='coverage_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='committeeinfo',
            name='coverage_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='committeeinfo',
            name='form_type',
            field=models.CharField(default='F99', max_length=3),
        ),
        migrations.AlterField(
            model_name='committeeinfo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='forms.F99Attachment/bytes/filename/mimetype', validators=[fecfiler.forms.validators.validate_is_pdf]),
        ),
    ]
