# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_auto_20181128_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeinfo',
            name='additional_email_1',
            field=models.TextField(default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='committeeinfo',
            name='additional_email_2',
            field=models.TextField(default='-', max_length=100, null=True),
        ),
    ]
