 export interface form99 {
  committeeid: string,
  committeename: string,
  street1: string,
  street2: string,
  city: string,
  state: string,
  zipcode: string,
  treasurerprefix: string,
  treasurerfirstname: string,
  reason: string,
  text: string,
  treasurermiddlename: string,
  treasurerlastname: string,
  treasurersuffix: string,
  signee: string,
  email_on_file: string,
  additional_email_1: string,
  additional_email_2: string,
  created_at: string,
  is_submitted: boolean
 }
