# Generated by Django 3.2.12 on 2022-07-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo_text', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memotext',
            old_name='report_id',
            new_name='report',
        ),
    ]
