# Generated by Django 5.2.11 on 2026-03-07 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('memo_text', '0002_initial'), ('memo_text', '0003_memotext_text_prefix')]

    dependencies = [
        ('memo_text', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memotext',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
        migrations.AddField(
            model_name='memotext',
            name='text_prefix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
