# Generated by Django 4.2.7 on 2024-01-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_text', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memotext',
            name='text_prefix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
