# Generated by Django 3.2.12 on 2022-09-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memo_text", "0002_memotext_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memotext",
            name="report",
            field=models.IntegerField(null=True),
        ),
    ]
