# Generated by Django 3.2.12 on 2022-09-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    def update_uuid(apps, schema_editor):
        F3XSummary = apps.get_model("f3x_summaries", "F3XSummary")
        MemoText = apps.get_model("memo_text", "MemoText")
        report_uuid = F3XSummary.objects.filter(
            id=models.OuterRef("report_old")
        ).values_list("uuid")[:1]
        MemoText.objects.update(report=models.Subquery(report_uuid))

    dependencies = [
        ("memo_text", "0003_report_id"),
        ("f3x_summaries", "0021_f3xsummary_uuid_primary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memotext",
            old_name="report",
            new_name="report_old",
        ),
        migrations.AddField(
            model_name="memotext",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.CASCADE,
                to="f3x_summaries.F3XSummary",
            ),
        ),
        migrations.RunPython(update_uuid),
        migrations.RemoveField(
            model_name="memotext",
            name="report_old",
        ),
    ]
