# Generated by Django 3.2.12 on 2022-09-15 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('f3x_summaries', '0025_auto_20220915_1309'),
        ('memo_text', '0006_committee_uuid_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memotext',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='memotext',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='memotext',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='f3x_summaries.f3xsummary'),
        ),
    ]
