# Generated by Django 3.2.12 on 2022-10-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_text', '0007_auto_20220915_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='memotext',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
