# Generated by Django 3.2.12 on 2022-11-03 14:46

from django.db import migrations, models


def set_is_report_level_memo(apps, _):
    memo_text = apps.get_model("memo_text", "memotext")
    for memo in memo_text.objects.all():
        memo.is_report_level_memo = memo.transaction_uuid is not None
        memo.save()


class Migration(migrations.Migration):

    dependencies = [
        ("memo_text", "0008_memotext_transaction_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="memotext",
            name="is_report_level_memo",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_is_report_level_memo, migrations.RunPython.noop),
    ]
