# Generated by Django 4.1.3 on 2023-04-27 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memo_text", "0009_memotext_report_level_memo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memotext",
            name="filer_committee_id_number",
        ),
    ]
