over_two_hundred_types = [
    "OPERATING_EXPENDITURE",
    "OPERATING_EXPENDITURE_PAYMENT_TO_PAYROLL_MEMO",
    "OPERATING_EXPENDITURE_VOID",
    "OTHER_DISBURSEMENT",
    "OTHER_DISBURSEMENT_VOID",
]
