over_two_hundred_types = [
    "OPERATING_EXPENDITURE",
    "OPERATING_EXPENDITURE_VOID",
    "OTHER_DISBURSEMENT",
    "OTHER_DISBURSEMENT_VOID",
    "OPERATING_EXPENDITURE_CREDIT_CARD_PAYMENT",
    "OPERATING_EXPENDITURE_PAYMENT_TO_PAYROLL",
    "OPERATING_EXPENDITURE_STAFF_REIMBURSEMENT",
]
