FROM python:3.13
ENV PYTHONUNBUFFERED=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PROJECT_ENVIRONMENT=/opt/venv \
    PATH="/opt/venv/bin:$PATH"

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN mkdir /opt/nxg_fec_e2e
WORKDIR /opt/nxg_fec_e2e

COPY pyproject.toml uv.lock /opt/
RUN uv sync --frozen --no-dev

RUN mv /etc/localtime /etc/localtime.backup && ln -s /usr/share/zoneinfo/EST5EDT /etc/localtime

RUN useradd nxgu --no-create-home --home /opt/nxg_fec_e2e && chown -R nxgu:nxgu /opt/nxg_fec_e2e
USER nxgu

EXPOSE 8080
ENTRYPOINT ["/bin/sh", "-c", "python manage.py migrate && python manage.py loaddata fixtures/user-data.json && python manage.py load_mocked_committee_data && gunicorn --bind 0.0.0.0:8080 fecfiler.wsgi -w $GUNICORN_WORKERS --threads=$GUNICORN_THREADS --reload"]
