#!/bin/bash

# change working directory to build the Angular application
cd front-end
# remove old artifact
rm -fr dist/* node_modules
# install dependencies
echo -e "installing npm dependecies \n"
npm install
# build the angular app
echo -e "building Angular app \n"
ng build
# change directory to the root of the project
cd ..
# shutdown running instances
docker-compose down
#  echo -e "Removing old images"
#  docker rmi -f $( docker images -qa )
#else
#  echo -e "Nothing to delete \n"s
#fi
# build the application
#docker-compose build
docker-compose up --build -d
# rerun the migrations just in case
API=$( docker ps | awk '/api/ { print $1 }' )
docker exec -ti $API python manage.py migrate --noinput
docker exec -ti $API python manage.py loaddata fixtures/base_data.json

sleep 2
echo -e "Running applications \n"
docker ps
