#!/bin/bash

# change working directory to build the Angular application
cd front-end
# remove old artifact
rm -fr dist/* node_modules
# install dependencies
echo -e "installing npm dependecies \n"
npm install
# build the angular app
echo -e "building Angular app \n"
$(npm bin)/ng build
# change directory to the root of the project
cd ..
# shutdown running instances
sudo docker-compose down
#  echo -e "Removing old images"
sudo sh -c "docker rmi -f $( docker images -qa )"
#else
#  echo -e "Nothing to delete \n"s
#fi
# build the application
sudo docker-compose build
sudo docker-compose up --build -d
# rerun the migrations just in case
sleep 2
sudo docker-compose exec api python manage.py migrate --noinput
sudo docker-compose exec api python manage.py loaddata fixtures/base_data.json

sleep 2
echo -e "Running applications \n"
sudo docker-compose ps
