[tool.black]
line-length = 90

[tool.deptry]
requirements_files_dev  = ["requirements-test.txt"]
known_first_party = ["fecfiler", "locust_data_generator"]
extend_exclude = ["pypi"]

[tool.deptry.per_rule_ignores]
DEP001 = ["locust"]
DEP002 = [
    "gunicorn",
    "django-deprecate-fields",
    "django-migration-linter"
]
