from fecfiler.transactions.models import Transaction
from fecfiler.contacts.models import Contact
from fecfiler.committee_accounts.models import CommitteeAccount


def get_test_transaction(
    transaction_type_identifier="INDIVIDUAL_RECEIPT",
    committee: CommitteeAccount | None = None,
):

    return Transaction(
        transaction_type_identifier=transaction_type_identifier,
        contact_1=Contact(
            committee_account=committee,
            candidate_id="1 candidate id",
            committee_id="1 committee id",
            name="1 name",
            last_name="1 last name",
            first_name="1 first name",
            middle_name="1 middle name",
            prefix="1 prefix",
            suffix="1 suffix",
            street_1="1 street 1",
            street_2="1 street 2",
            city="1 city",
            state="1 state",
            zip="1 zip",
            employer="1 employer",
            occupation="1 occupation",
            candidate_office="1 candidate office",
            candidate_state="1 candidate state",
            candidate_district="1 candidate district",
            telephone="1 telephone",
            country="1 country",
        ),
        contact_2=Contact(
            committee_account=committee,
            candidate_id="2 candidate id",
            committee_id="2 committee id",
            name="2 name",
            last_name="2 last name",
            first_name="2 first name",
            middle_name="2 middle name",
            prefix="2 prefix",
            suffix="2 suffix",
            street_1="2 street 1",
            street_2="2 street 2",
            city="2 city",
            state="2 state",
            zip="2 zip",
            employer="2 employer",
            occupation="2 occupation",
            candidate_office="2 candidate office",
            candidate_state="2 candidate state",
            candidate_district="2 candidate district",
            telephone="2 telephone",
            country="2 country",
        ),
        contact_3=Contact(
            committee_account=committee,
            candidate_id="3 candidate id",
            committee_id="3 committee id",
            name="3 name",
            last_name="3 last name",
            first_name="3 first name",
            middle_name="3 middle name",
            prefix="3 prefix",
            suffix="3 suffix",
            street_1="3 street 1",
            street_2="3 street 2",
            city="3 city",
            state="3 state",
            zip="3 zip",
            employer="3 employer",
            occupation="3 occupation",
            candidate_office="3 candidate office",
            candidate_state="3 candidate state",
            candidate_district="3 candidate district",
            telephone="3 telephone",
            country="3 country",
        ),
    )
