export interface IAccount{
    committeeid: string;
    committeename: string;
    street1: string;
    street2: string;
    city: string;
    state: string;
    zipcode: string;
    treasurerprefix: string;
    treasurerfirstname: string;
    treasurermiddlename: string;
    treasurerlastname: string;
    treasurersuffix: string;
    email_on_file: string;
    email_on_file1: string;
    created_at: string;
    treasurerstreet1: string;
    treasurerstreet2: string;
    treasurercity: string;
    treasurerstate: string;
    treasurerzipcode: string;
    bankName: string;
    bankAddress1: string;
    bankAddress2: string;
    bankCity: string;
    bankState: string;
    bankZip: string;
    candidatePrefix: string;
    fax: string;
    treasurerphone: string;
    website: string;
}
 export class Account implements IAccount {
    public committeeid: string;
    public committeename: string;
    public street1: string;
    public street2: string;
    public city: string;
    public state: string;
    public zipcode: string;
    public treasurerprefix: string;
    public treasurerfirstname: string;
    public treasurermiddlename: string;
    public treasurerlastname: string;
    public treasurersuffix: string;
    public email_on_file: string;
    public email_on_file1: string;
    public created_at: string;
    public treasurerstreet1: string;
    public treasurerstreet2: string;
    public treasurercity: string;
    public treasurerstate: string;
    public treasurerzipcode: string;
    public bankName: string;
    public bankAddress1: string;
    public bankAddress2: string;
    public bankCity: string;
    public bankState: string;
    public bankZip: string;
    public candidatePrefix: string;
    public fax: string;
    public treasurerphone: string;
    public website: string;
 }
