# Generated by Django 5.1.1 on 2024-11-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_on_hand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashonhandyearly',
            name='cash_on_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashonhandyearly',
            name='year',
            field=models.TextField(default=2020, unique=True),
            preserve_default=False,
        ),
    ]
