# Generated by Django 5.1.1 on 2024-11-07 12:43

import django.utils.timezone
from django.db import migrations, models


def copy_cash_on_hand_yearly(apps, _):
    CashOnHandYearly = apps.get_model("cash_on_hand", "CashOnHandYearly")
    for cash_on_hand_yearly in CashOnHandYearly.objects.all():
        if not cash_on_hand_yearly.cash_on_hand or not cash_on_hand_yearly.year:
            cash_on_hand_yearly.delete()

        cash_on_hand_yearly.cash_on_hand_copy = cash_on_hand_yearly.cash_on_hand
        cash_on_hand_yearly.year_copy = cash_on_hand_yearly.year
        cash_on_hand_yearly.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cash_on_hand", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashonhandyearly",
            name="cash_on_hand_copy",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=11, null=False, blank=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cashonhandyearly",
            name="year_copy",
            field=models.TextField(
                default=django.utils.timezone.now, null=False, blank=False
            ),
            preserve_default=False,
        ),
        migrations.RunPython(copy_cash_on_hand_yearly),
        migrations.RemoveField(model_name="cashonhandyearly", name="cash_on_hand"),
        migrations.RemoveField(model_name="cashonhandyearly", name="year"),
    ]
