# Generated by Django 5.1.1 on 2024-11-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_on_hand', '0002_alter_cashonhandyearly_cash_on_hand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashonhandyearly',
            name='updated',
        ),
    ]
