# Generated by Django 5.1.1 on 2024-11-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_on_hand', '0002_alter_cashonhandyearly_cash_on_hand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashonhandyearly',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
