# Generated by Django 5.1.1 on 2024-11-29 19:25

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('cash_on_hand', '0003_alter_cashonhandyearly_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashonhandyearly',
            name='updated',
        ),
        linter.IgnoreMigration(),
    ]
