# Generated by Django 3.2.12 on 2022-12-13 22:39

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0010_auto_20220915_1309"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("memo_text", "0009_memotext_report_level_memo"),
        ("committee_accounts", "0005_rename_uuid_committeeaccount_id"),
        ("f3x_summaries", "0026_auto_20221130_1459"),
    ]

    operations = []
