# Generated by Django 3.2.12 on 2022-12-13 22:39

from django.db import migrations
from django.db.models import F, Value
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import management


def copy_scha_transactions(apps, schema_editor):
    # update contenttype table to have scheduleatransaction entry
    app_config = apps.get_app_config("transactions")
    if not hasattr(app_config, "models_module"):
        app_config.models_module = True
    management.create_contenttypes(app_config)
    if app_config.models_module is True:
        app_config.models_module = None

    try:
        SchATransaction = apps.get_model("scha_transactions", "SchATransaction")  # noqa
        ScheduleATransaction = apps.get_model(  # noqa
            "transactions", "ScheduleATransaction"
        )
        content_type = ContentType.objects.get(
            app_label="transactions", model="scheduleatransaction"
        )
        transactions_to_copy = SchATransaction.objects.all().annotate(
            conduit_street_1=F("conduit_street1"),
            conduit_street_2=F("conduit_street2"),
            parent_transaction_object_id=F("parent_transaction_id"),
            parent_transaction_content_type_id=Value(content_type.id),
        )
        ScheduleATransaction.objects.bulk_create(transactions_to_copy)
    except LookupError:
        print("No SchATransaction table to copy")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copy_scha_transactions, migrations.RunPython.noop),
    ]
