# Generated by Django 3.2.12 on 2022-12-13 22:39

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
    ]
