# Generated by Django 5.2.11 on 2026-03-07 03:25

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import connection, migrations, models
from fecfiler.transactions.schedule_a.managers import (
    over_two_hundred_types as schedule_a_over_two_hundred_types,
)
from fecfiler.transactions.schedule_b.managers import (
    over_two_hundred_types as schedule_b_over_two_hundred_types,
)


# Inlined from 0011_transaction_can_delete
# Keep the final live trigger that maintains Transaction.blocking_reports.
def create_trigger_function(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
        CREATE OR REPLACE FUNCTION update_transactions_can_delete() RETURNS TRIGGER AS $$
        BEGIN
            UPDATE transactions_transaction
            SET blocking_reports = CASE
                WHEN NEW.upload_submission_id IS NOT NULL
                THEN array_append(blocking_reports, NEW.id)
                ELSE array_remove(blocking_reports, NEW.id)
            END
            -- all transactions in the submitted report
            WHERE id IN (
                SELECT transaction_id
                FROM reports_reporttransaction
                WHERE report_id = NEW.id
            )
            -- all transactions that are reattributed in the submitted report
            OR id IN (
                SELECT reatt_redes_id
                FROM reports_reporttransaction
                JOIN transactions_transaction tt
                ON reports_reporttransaction.transaction_id = tt.id
                WHERE report_id = NEW.id
            )
            -- all loans that are carried forward in the submitted report
            OR id IN (
                SELECT loan_id
                FROM reports_reporttransaction
                JOIN transactions_transaction tt
                ON reports_reporttransaction.transaction_id = tt.id
                WHERE report_id = NEW.id
            )
            -- all repayments to loans that are carried forward in the submitted report
            OR loan_id IN (
                SELECT loan_id
                FROM reports_reporttransaction
                JOIN transactions_transaction tt
                ON reports_reporttransaction.transaction_id = tt.id
                WHERE report_id = NEW.id AND tt.schedule_c_id IS NOT NULL
            )
            -- all debts that are carried forward in the submitted report
            OR id IN (
                SELECT debt_id
                FROM reports_reporttransaction
                JOIN transactions_transaction tt
                ON reports_reporttransaction.transaction_id = tt.id
                WHERE report_id = NEW.id
            )
            -- all repayments to debts that are carried forward in the submitted report
            OR debt_id IN (
                SELECT debt_id
                FROM reports_reporttransaction
                JOIN transactions_transaction tt
                ON reports_reporttransaction.transaction_id = tt.id
                WHERE report_id = NEW.id AND tt.schedule_d_id IS NOT NULL
            );
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
        )


def drop_trigger_function(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("DROP FUNCTION IF EXISTS update_transactions_can_delete();")


def create_trigger(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE TRIGGER report_status_update
            AFTER UPDATE OF upload_submission_id ON reports_report
            FOR EACH ROW
            EXECUTE FUNCTION update_transactions_can_delete();
            """
        )


def drop_trigger(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("DROP TRIGGER IF EXISTS report_status_update ON reports_report;")


# Inlined from 0013_transaction_itemized_and_associated_triggers
# This data is used by itemization logic and should exist on fresh installs.
def populate_over_two_hundred_types(apps, schema_editor):
    OverTwoHundredTypesScheduleA = apps.get_model(  # noqa: N806
        "transactions", "OverTwoHundredTypesScheduleA"
    )
    OverTwoHundredTypesScheduleB = apps.get_model(  # noqa: N806
        "transactions", "OverTwoHundredTypesScheduleB"
    )
    scha_types_to_create = [
        OverTwoHundredTypesScheduleA(type=type_to_create)
        for type_to_create in schedule_a_over_two_hundred_types
    ]
    OverTwoHundredTypesScheduleA.objects.bulk_create(scha_types_to_create)
    schb_types_to_create = [
        OverTwoHundredTypesScheduleB(type=type_to_create)
        for type_to_create in schedule_b_over_two_hundred_types
    ]
    OverTwoHundredTypesScheduleB.objects.bulk_create(schb_types_to_create)


class Migration(migrations.Migration):

    replaces = [
        ("transactions", "0002_remove_schedulea_contributor_city_and_more"),
        ("transactions", "0003_alter_transaction_parent_transaction"),
        ("transactions", "0004_report_transactions_link_table"),
        ("transactions", "0005_schedulec_report_coverage_from_date_and_more"),
        ("transactions", "0006_independent_expenditure_memos_no_aggregation_group"),
        ("transactions", "0007_schedulee_so_candidate_state"),
        ("transactions", "0008_transaction__calendar_ytd_per_election_office_and_more"),
        ("transactions", "0009_update_calculate_loan_payment_to_date"),
        ("transactions", "0010_update_aggregate_trigger_performance"),
        ("transactions", "0011_transaction_can_delete"),
        ("transactions", "0012_alter_transactions_blocking_reports"),
        ("transactions", "0013_transaction_itemized_and_associated_triggers"),
        ("transactions", "0014_drop_transaction_view"),
        ("transactions", "0015_merge_transaction_triggers"),
        ("transactions", "0016_schedulef_transaction_contact_4_and_more"),
        ("transactions", "0017_schedulef_coordianted_to_coordinated"),
        ("transactions", "0018_schedulef_general_election_year_and_more"),
        ("transactions", "0019_aggregate_committee_controls"),
        ("transactions", "0020_trigger_save_on_transactions"),
        ("transactions", "0021_alter_transaction_reports"),
        ("transactions", "0022_schedule_f_aggregation"),
        ("transactions", "0023_optimize_calculate_loan_payment_to_date"),
        ("transactions", "0024_scheduled_balance_at_close_and_more"),
        ("transactions", "0025_drop_aggregate_triggers"),
        ("transactions", "0026_alter_transaction_itemized"),
    ]

    dependencies = [
        ("contacts", "0001_initial"),
        ("reports", "0005_remove_form1m_squashed_0006_reporttransaction"),
        ("reports", "0007_remove_report_deleted_squashed_00019_form24_name_fix"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reports",
            field=models.ManyToManyField(
                related_name="transactions",
                through="reports.ReportTransaction",
                through_fields=["transaction", "report"],
                to="reports.report",
            ),
        ),
        migrations.AddField(
            model_name="schedulec",
            name="report_coverage_through_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduled",
            name="report_coverage_from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedulee",
            name="so_candidate_state",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="_calendar_ytd_per_election_office",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="aggregate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="loan_payment_to_date",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="blocking_reports",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=list, size=None
            ),
        ),
        migrations.RunPython(
            code=create_trigger_function,
            reverse_code=drop_trigger_function,
        ),
        migrations.RunPython(
            code=create_trigger,
            reverse_code=drop_trigger,
        ),
        migrations.AddField(
            model_name="transaction",
            name="itemized",
            field=models.BooleanField(db_default=False),
        ),
        migrations.CreateModel(
            name="OverTwoHundredTypesScheduleA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("type", models.TextField()),
            ],
            options={
                "db_table": "over_two_hundred_types_schedulea",
                "indexes": [
                    models.Index(fields=["type"], name="over_two_hu_type_2c8314_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="OverTwoHundredTypesScheduleB",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("type", models.TextField()),
            ],
            options={
                "db_table": "over_two_hundred_types_scheduleb",
                "indexes": [
                    models.Index(fields=["type"], name="over_two_hu_type_411a44_idx")
                ],
            },
        ),
        migrations.RunPython(
            code=populate_over_two_hundred_types,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name="ScheduleF",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "filer_designated_to_make_coordinated_expenditures",
                    models.BooleanField(blank=True, null=True),
                ),
                ("expenditure_date", models.DateField(blank=True, null=True)),
                (
                    "expenditure_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "aggregate_general_elec_expended",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                ("expenditure_purpose_descrip", models.TextField(blank=True)),
                ("category_code", models.TextField(blank=True, null=True)),
                ("memo_text_description", models.TextField(blank=True, null=True)),
                ("general_election_year", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="schedule_f",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.schedulef",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="contact_4",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_4_transaction_set",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="contact_5",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_5_transaction_set",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="scheduled",
            name="balance_at_close",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="scheduled",
            name="beginning_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="scheduled",
            name="incurred_prior",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="scheduled",
            name="payment_prior",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="scheduled",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
    ]
