# Generated by Django 4.2.7 on 2024-01-05 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_remove_schedulea_contributor_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="parent_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="transactions.transaction",
            ),
        ),
    ]
