# Generated by Django 5.2.12 on 2026-03-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0002_remove_schedulea_squashed_0026_alter_transaction_itemized",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS
                    public.calculate_calendar_ytd_per_election_office CASCADE;
                DROP FUNCTION IF EXISTS public.calculate_entity_aggregates CASCADE;
                DROP FUNCTION IF EXISTS public.calculate_is_loan CASCADE;
                DROP FUNCTION IF EXISTS public.calculate_itemization CASCADE;
                DROP FUNCTION IF EXISTS public.calculate_loan_date CASCADE;
                DROP FUNCTION IF EXISTS public.calculate_loan_payment_to_date CASCADE;
                DROP FUNCTION IF EXISTS public.calculate_original_loan_id CASCADE;
                DROP FUNCTION IF EXISTS
                    public.get_children_and_grandchildren_transaction_ids CASCADE;
                DROP FUNCTION IF EXISTS
                    public.get_parent_grandparent_transaction_ids CASCADE;
                DROP FUNCTION IF EXISTS public.get_temp_tablename CASCADE;
                DROP FUNCTION IF EXISTS public.handle_parent_itemization CASCADE;
                DROP FUNCTION IF EXISTS public.needs_itemized_set CASCADE;
                DROP FUNCTION IF EXISTS public.process_itemization CASCADE;
                DROP FUNCTION IF EXISTS public.set_itemization_for_ids CASCADE;
            """,
        ),
    ]
