# Generated by Django 5.2.13 on 2026-05-14 13:37

from django.db import migrations, models


def set_interest_rate_is_percent(apps, schema_editor):
    ScheduleC = apps.get_model(  # noqa: N806
        "transactions.ScheduleC"
    )
    ScheduleC1 = apps.get_model(  # noqa: N806
        "transactions.ScheduleC1"
    )

    ScheduleC.objects.all().update(loan_interest_rate_is_percent=False)
    ScheduleC1.objects.all().update(loan_interest_rate_is_percent=False)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_unused_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulec',
            name='loan_due_date_is_date',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulec',
            name='loan_interest_rate_is_percent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulec1',
            name='loan_due_date_is_date',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulec1',
            name='loan_interest_rate_is_percent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.RunPython(
            set_interest_rate_is_percent,
            migrations.RunPython.noop
        )
    ]
