# Generated by Django 4.2.10 on 2024-03-25 16:45

from django.db import migrations
from django.db.models import Q, deletion, DateField, ForeignKey, ManyToManyField


def set_coverage_date(apps, schema_editor):
    transaction_model = apps.get_model("transactions", "Transaction")

    for transaction in transaction_model.objects.filter(
        Q(schedule_c__isnull=False) | Q(schedule_d__isnull=False)
    ):
        for report in transaction.reports:
            if report.coverage_from_date:
                schedule = transaction.schedule_d or transaction.schedule_c
                schedule.report_coverage_from_date = report.coverage_from_date
                schedule.save()
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_reporttransaction"),
        ("transactions", "0004_report_transactions_link_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulec",
            name="report_coverage_from_date",
            field=DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduled",
            name="report_coverage_from_date",
            field=DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="parent_transaction",
            field=ForeignKey(
                blank=True,
                null=True,
                on_delete=deletion.CASCADE,
                to="transactions.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reports",
            field=ManyToManyField(
                related_name="transactions",
                through="reports.ReportTransaction",
                to="reports.report",
            ),
        ),
        migrations.RunPython(set_coverage_date, migrations.RunPython.noop),
    ]
