# Generated by Django 4.1.3 on 2023-03-08 13:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_scheduleb_delete_schedulebtransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("receipt_line_number", models.TextField(blank=True, null=True)),
                ("lender_organization_name", models.TextField(blank=True, null=True)),
                ("lender_last_name", models.TextField(blank=True, null=True)),
                ("lender_first_name", models.TextField(blank=True, null=True)),
                ("lender_middle_name", models.TextField(blank=True, null=True)),
                ("lender_prefix", models.TextField(blank=True, null=True)),
                ("lender_suffix", models.TextField(blank=True, null=True)),
                ("lender_street_1", models.TextField(blank=True, null=True)),
                ("lender_street_2", models.TextField(blank=True, null=True)),
                ("lender_city", models.TextField(blank=True, null=True)),
                ("lender_state", models.TextField(blank=True, null=True)),
                ("lender_zip", models.TextField(blank=True, null=True)),
                ("election_code", models.TextField(blank=True, null=True)),
                ("election_other_description", models.TextField(blank=True, null=True)),
                (
                    "loan_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                ("loan_payment_to_date", models.TextField(blank=True, null=True)),
                (
                    "loan_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                ("loan_incurred_date", models.DateField(blank=True, null=True)),
                ("loan_due_date", models.DateField(blank=True, null=True)),
                (
                    "loan_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=14, max_digits=14, null=True
                    ),
                ),
                ("secured", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "personal_funds",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("lender_committee_id_number", models.TextField(blank=True, null=True)),
                ("lender_candidate_id_number", models.TextField(blank=True, null=True)),
                ("lender_candidate_last_name", models.TextField(blank=True, null=True)),
                (
                    "lender_candidate_first_name",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "lender_candidate_middle_name",
                    models.TextField(blank=True, null=True),
                ),
                ("lender_candidate_prefix", models.TextField(blank=True, null=True)),
                ("lender_candidate_suffix", models.TextField(blank=True, null=True)),
                ("lender_candidate_office", models.TextField(blank=True, null=True)),
                ("lender_candidate_state", models.TextField(blank=True, null=True)),
                ("lender_candidate_district", models.TextField(blank=True, null=True)),
                ("memo_text_description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="schedule_c",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.schedulec",
            ),
        ),
    ]
