# Generated by Django 5.2.13 on 2026-05-14 13:37

from django.db import migrations


def rename_transaction_types(apps, schema_editor):
    transaction = apps.get_model("transactions", "Transaction")

    type_mapping = {
        "RECEIPT_FROM_UNREGISTERED_ENTITY": "RECEIPT_FROM_UNREGISTERED_ORGANIZATION",
        "RECEIPT_FROM_UNREGISTERED_ENTITY_RETURN": (
            "RECEIPT_FROM_UNREGISTERED_ORGANIZATION_RETURN"
        ),
        "REFUND_UNREGISTERED_CONTRIBUTION": (
            "REFUND_RECEIPTS_FROM_UNREGISTERED_ORGANIZATION"
        ),
        "REFUND_UNREGISTERED_CONTRIBUTION_VOID": (
            "REFUND_RECEIPTS_FROM_UNREGISTERED_ORGANIZATION_VOID"
        ),
    }

    for old_value, new_value in type_mapping.items():
        transaction.objects.filter(transaction_type_identifier=old_value).update(
            transaction_type_identifier=new_value
        )


def reverse_rename_transaction_types(apps, schema_editor):
    transaction = apps.get_model("transactions", "Transaction")

    reverse_mapping = {
        "RECEIPT_FROM_UNREGISTERED_ORGANIZATION": "RECEIPT_FROM_UNREGISTERED_ENTITY",
        "RECEIPT_FROM_UNREGISTERED_ORGANIZATION_RETURN": (
            "RECEIPT_FROM_UNREGISTERED_ENTITY_RETURN"
        ),
        "REFUND_RECEIPTS_FROM_UNREGISTERED_ORGANIZATION": (
            "REFUND_UNREGISTERED_CONTRIBUTION"
        ),
        "REFUND_RECEIPTS_FROM_UNREGISTERED_ORGANIZATION_VOID": (
            "REFUND_UNREGISTERED_CONTRIBUTION_VOID"
        ),
    }

    for old_value, new_value in reverse_mapping.items():
        transaction.objects.filter(transaction_type_identifier=old_value).update(
            transaction_type_identifier=new_value
        )


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_schedulec_loan_due_date_is_date_and_more"),
    ]

    operations = [
        migrations.RunPython(
            rename_transaction_types, reverse_code=reverse_rename_transaction_types
        ),
    ]
