# Generated by Django 4.1.3 on 2023-03-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_schedulec_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(
                fields=['form_type'],
                name='transaction_form_ty_4e50e4_idx'
            ),
        ),
    ]
