# Generated by Django 4.2.11 on 2024-06-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0006_independent_expenditure_memos_no_aggregation_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulee",
            name="so_candidate_state",
            field=models.TextField(blank=True, null=True),
        ),
    ]
