# Generated by Django 5.2.13 on 2026-05-14 13:37

from django.db import migrations


def rename_transaction_types(apps, schema_editor):
    transaction = apps.get_model("transactions", "Transaction")

    type_mapping = {
        "REFUND_RECEIPTS_FROM_UNREGISTERED_ORGANIZATION": (
            "REFUND_RECEIPT_FROM_UNREGISTERED_ORGANIZATION"
        ),
        "REFUND_RECEIPTS_FROM_UNREGISTERED_ORGANIZATION_VOID": (
            "REFUND_RECEIPT_FROM_UNREGISTERED_ORGANIZATION_VOID"
        ),
    }

    for old_value, new_value in type_mapping.items():
        transaction.objects.filter(transaction_type_identifier=old_value).update(
            transaction_type_identifier=new_value
        )


def reverse_rename_transaction_types(apps, schema_editor):
    transaction = apps.get_model("transactions", "Transaction")

    reverse_mapping = {
        "REFUND_RECEIPT_FROM_UNREGISTERED_ORGANIZATION": (
            "REFUND_RECEIPTS_FROM_UNREGISTERED_ORGANIZATION"),
        "REFUND_RECEIPT_FROM_UNREGISTERED_ORGANIZATION_VOID": (
            "REFUND_RECEIPTS_FROM_UNREGISTERED_ORGANIZATION_VOID"
        ),
    }

    for old_value, new_value in reverse_mapping.items():
        transaction.objects.filter(transaction_type_identifier=old_value).update(
            transaction_type_identifier=new_value
        )


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_update_transaction_type_for_name_change"),
    ]

    operations = [
        migrations.RunPython(
            rename_transaction_types, reverse_code=reverse_rename_transaction_types
        ),
    ]
