# Generated by Django 4.1.3 on 2023-04-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_rename_benificiary_candidate_district_scheduleb_'
                         'beneficiary_candidate_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='force_itemized',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
