# Generated by Django 4.1.3 on 2023-04-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transactions",
            "0008_rename_benificiary_candidate_district_scheduleb_beneficiary_candidate_district_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="filer_committee_id_number",
        ),
    ]
