# Generated by Django 5.2.17 on 2026-09-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_s_from_refund_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='line',
            field=models.TextField(blank=True, null=True),
        ),
    ]
