# Generated by Django 4.1.3 on 2023-05-03 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0009_remove_scheduleatransaction_aggregation_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="back_reference_sched_name",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="back_reference_tran_id_number",
        ),
    ]
