# Generated by Django 4.1.3 on 2023-06-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_contact_id'),
        ('transactions', '0010_remove_filer_id_and_back_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='contact',
            new_name='contact_1',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contact_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_1_transaction_set', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contact_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_2_transaction_set', to='contacts.contact'),
        ),
    ]
