# Generated by Django 4.1.3 on 2023-05-30 20:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_remove_filer_id_and_back_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleC1",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("lender_organization_name", models.TextField(blank=True, null=True)),
                ("lender_street_1", models.TextField(blank=True, null=True)),
                ("lender_street_2", models.TextField(blank=True, null=True)),
                ("lender_city", models.TextField(blank=True, null=True)),
                ("lender_state", models.TextField(blank=True, null=True)),
                ("lender_zip", models.TextField(blank=True, null=True)),
                (
                    "loan_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "loan_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=14, max_digits=14, null=True
                    ),
                ),
                ("loan_incurred_date", models.DateField(blank=True, null=True)),
                ("loan_due_date", models.DateField(blank=True, null=True)),
                (
                    "loan_restructured",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "loan_originally_incurred_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "credit_amount_this_draw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "total_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "others_liable",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "collateral",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("desc_collateral", models.TextField(blank=True, null=True)),
                (
                    "collateral_value_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "perfected_interest",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "future_income",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "desc_specification_of_the_above",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "depository_account_established_date",
                    models.DateField(blank=True, null=True),
                ),
                ("ind_name_account_location", models.TextField(blank=True, null=True)),
                ("account_street_1", models.TextField(blank=True, null=True)),
                ("account_street_2", models.TextField(blank=True, null=True)),
                ("account_city", models.TextField(blank=True, null=True)),
                ("account_state", models.TextField(blank=True, null=True)),
                ("account_zip", models.TextField(blank=True, null=True)),
                (
                    "dep_acct_auth_date_presidential",
                    models.DateField(blank=True, null=True),
                ),
                ("basis_of_loan_description", models.TextField(blank=True, null=True)),
                ("treasurer_last_name", models.TextField(blank=True, null=True)),
                ("treasurer_first_name", models.TextField(blank=True, null=True)),
                ("treasurer_middle_name", models.TextField(blank=True, null=True)),
                ("treasurer_prefix", models.TextField(blank=True, null=True)),
                ("treasurer_suffix", models.TextField(blank=True, null=True)),
                ("treasurer_date_signed", models.DateField(blank=True, null=True)),
                ("authorized_last_name", models.TextField(blank=True, null=True)),
                ("authorized_first_name", models.TextField(blank=True, null=True)),
                ("authorized_middle_name", models.TextField(blank=True, null=True)),
                ("authorized_prefix", models.TextField(blank=True, null=True)),
                ("authorized_suffix", models.TextField(blank=True, null=True)),
                ("authorized_title", models.TextField(blank=True, null=True)),
                ("authorized_date_signed", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="schedule_c1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.schedulec1",
            ),
        ),
    ]
