# Generated by Django 4.1.3 on 2023-05-31 20:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0011_schedulec1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleC2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("guarantor_last_name", models.TextField(blank=True, null=True)),
                ("guarantor_first_name", models.TextField(blank=True, null=True)),
                ("guarantor_middle_name", models.TextField(blank=True, null=True)),
                ("guarantor_prefix", models.TextField(blank=True, null=True)),
                ("guarantor_suffix", models.TextField(blank=True, null=True)),
                ("guarantor_street_1", models.TextField(blank=True, null=True)),
                ("guarantor_street_2", models.TextField(blank=True, null=True)),
                ("guarantor_city", models.TextField(blank=True, null=True)),
                ("guarantor_state", models.TextField(blank=True, null=True)),
                ("guarantor_zip", models.TextField(blank=True, null=True)),
                ("guarantor_employer", models.TextField(blank=True, null=True)),
                ("guarantor_occupation", models.TextField(blank=True, null=True)),
                (
                    "guaranteed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="schedule_c2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.schedulec2",
            ),
        ),
    ]
