# Generated by Django 4.1.3 on 2023-06-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0013_remove_contact_add_contact_1_contact_2"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction", name="transaction_form_ty_4e50e4_idx"
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="form_type",
            new_name="_form_type",
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["_form_type"], name="transaction_form_ty_4e50e4_idx"
            ),
        ),
    ]
