# Generated by Django 4.1.3 on 2023-07-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_contact_id'),
        ('transactions', '0015_update_partnership_memo_to_partnership_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contact_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_3_transaction_set', to='contacts.contact'),
        )
    ]
