# Generated by Django 4.1.3 on 2023-07-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0015_update_partnership_memo_to_partnership_attribution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulec",
            name="loan_due_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedulec",
            name="loan_interest_rate",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedulec",
            name="loan_payment_to_date",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
    ]
