# Generated by Django 5.2 on 2025-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_form99_swap_text_code'),
        ('transactions', '0020_trigger_save_on_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reports',
            field=models.ManyToManyField(
                related_name='transactions',
                through='reports.ReportTransaction',
                through_fields=['transaction', 'report'],
                to='reports.report'
            ),
        ),
    ]
