# Generated by Django 4.1.3 on 2023-09-01 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0020_add_contact_3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulec",
            name="loan_balance",
        ),
        migrations.RemoveField(
            model_name="schedulec",
            name="loan_payment_to_date",
        ),
    ]
