# Generated by Django 4.1.3 on 2023-09-19 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0021_remove_loan_ptd_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="debt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debt_repayments",
                to="transactions.transaction",
            ),
        ),
    ]
