# Generated by Django 4.1.3 on 2023-09-01 16:24

from django.db import migrations, models
import fecfiler.shared.utilities
import django.db.models.deletion

# When we pull forward loans from one report to a new report, we need to be
# able to save the same transaction_id to the new loan record in the new
# report. Here we drop the unique constraint and index on transaction_id
# and create a new non-unique index.


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0022_add_debt_foreign_key"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE transactions_transaction "
            "DROP CONSTRAINT IF EXISTS "
            "transactions_transaction_transaction_id_key;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS "
            "transactions_transaction_transaction_id_non_unique "
            "ON transactions_transaction (transaction_id);"
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.TextField(default=fecfiler.shared.utilities.generate_fec_uid),
        ),
        migrations.AddField(
            model_name="transaction",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans_pulled_forward",
                to="transactions.transaction",
            ),
        ),
    ]
