# Generated by Django 4.1.3 on 2023-10-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report'),
        ('transactions', '0022_rename_transaction_form_ty_4e50e4_idx_transaction__form_t_e73a46_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
    ]
