# Generated by Django 5.2.7 on 2025-11-25 03:23

from django.db import migrations, models
from fecfiler.transactions.aggregation import process_aggregation_for_debts


def run_aggregations_for_all_debts(apps, schema_editor):
    transaction = apps.get_model("transactions", "Transaction")
    all_root_debts = transaction.objects.filter(
        schedule_d__isnull=False, debt__isnull=True
    )
    for debt in all_root_debts:
        process_aggregation_for_debts(debt)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_optimize_calculate_loan_payment_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='balance_at_close',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='beginning_balance',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='incurred_prior',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='payment_prior',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='payment_amount',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.RunPython(run_aggregations_for_all_debts, migrations.RunPython.noop)
    ]
