# Generated by Django 4.1.3 on 2023-09-25 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0023_add_loan_foreign_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduled",
            name="balance_at_close",
        ),
        migrations.RemoveField(
            model_name="scheduled",
            name="beginning_balance",
        ),
        migrations.RemoveField(
            model_name="scheduled",
            name="payment_amount",
        ),
    ]
