# Generated by Django 5.2.7 on 2025-11-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_optimize_calculate_loan_payment_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='balance_at_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='beginning_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='incurred_prior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='payment_prior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
