# Generated by Django 4.1.3 on 2023-09-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0024_remove_just_in_time_sch_d_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="force_unaggregated",
            field=models.BooleanField(blank=True, null=True),
        )
    ]
