# Generated by Django 4.1.3 on 2023-09-27 19:51

from django.db import migrations, models
from django.db.models import Value


def move_parent_to_loan(apps, schema_editor):
    Transaction = apps.get_model("transactions", "Transaction")  # noqa
    for loan_repayment in Transaction.objects.all().filter(
        transaction_type_identifier__in=[
            "LOAN_REPAYMENT_RECEIVED",
            "LOAN_REPAYMENT_MADE",
        ]
    ):
        loan_repayment.loan = loan_repayment.parent_transaction
        del loan_repayment.parent_transaction
        del loan_repayment.parent_transaction_id
        loan_repayment.save()


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0025_add_force_unaggregated_field"),
    ]

    operations = [migrations.RunPython(move_parent_to_loan)]
