# Generated by Django 5.2.9 on 2025-12-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0025_drop_aggregate_triggers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="itemized",
            field=models.BooleanField(db_default=False),
        ),
    ]
