# Generated by Django 5.2.9 on 2026-01-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_scheduled_balance_at_close_and_more'),
        ('transactions', '0025_alter_transaction_itemized'),
    ]

    operations = [
    ]
