# Generated by Django 4.1.3 on 2023-10-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_use_debt_loan_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction__form_t_e73a46_idx',
            old_name='transaction_form_ty_4e50e4_idx',
        ),
    ]
