# Generated by Django 4.1.3 on 2023-06-05 20:15

from django.db import migrations


ttis_to_change = {
    "UNREGISTERED_RECEIPT_FROM_PERSON": "RECEIPT_FROM_UNREGISTERED_ENTITY",
    "UNREGISTERED_RECEIPT_FROM_PERSON_RETURN": "RECEIPT_FROM_UNREGISTERED_ENTITY_RETURN",
}


def update_ttis(apps, schema_editor):  # noqa
    Transaction = apps.get_model("transactions", "Transaction")  # noqa
    for transaction in Transaction.objects.all():
        keys = list(ttis_to_change.keys())
        if transaction.transaction_type_identifier in keys:
            new_tti = ttis_to_change[transaction.transaction_type_identifier]
            transaction.transaction_type_identifier = new_tti
            transaction.save()


def reverse_ttis(apps, schema_editor):  # noqa
    reverse_ttis_to_change = {}
    for key in ttis_to_change:
        value = ttis_to_change[key]
        reverse_ttis_to_change[value] = key

    Transaction = apps.get_model("transactions", "Transaction")  # noqa
    for transaction in Transaction.objects.all():
        keys = list(reverse_ttis_to_change.keys())
        if transaction.transaction_type_identifier in keys:
            new_tti = reverse_ttis_to_change[transaction.transaction_type_identifier]
            transaction.transaction_type_identifier = new_tti
            transaction.save()


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0028_alter_transaction_report"),
    ]

    operations = [migrations.RunPython(update_ttis, reverse_code=reverse_ttis)]
