# Generated by Django 4.1.3 on 2023-10-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_update_receipt_from_person_to_receipt_from_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulee',
            name='calendar_ytd',
        ),
    ]
