# Generated by Django 4.1.3 on 2023-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_remove_schedulee_calendar_ytd'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulea',
            name='reattribution_redesignation_tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='reattribution_redesignation_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
