# Generated by Django 4.1.3 on 2023-11-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0033_remove_receipt_line_number_from_loans_by_committee"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reatt_redes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reatt_redes_associations",
                to="transactions.transaction",
            ),
        ),
    ]
