# Generated by Django 4.2.7 on 2024-01-05 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_add_reattr_redes_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='transactions.transaction'),
        ),
    ]
