# Generated by Django 3.2.12 on 2022-06-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f3x_summaries', '0010_auto_20220525_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f3xsummary',
            name='coverage_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='f3xsummary',
            name='coverage_through_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='f3xsummary',
            name='date_of_election',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='f3xsummary',
            name='date_signed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
