# Generated by Django 3.2.12 on 2022-09-09 16:41

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    F3XSummary = apps.get_model("f3x_summaries", "F3XSummary")  # noqa
    for f3xsummary in F3XSummary.objects.all():
        f3xsummary.uuid = uuid.uuid4()
        f3xsummary.save()


class Migration(migrations.Migration):

    dependencies = [
        ("f3x_summaries", "0017_f3xsummary_calculation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="f3xsummary",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(create_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="f3xsummary",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
