# Generated by Django 3.2.12 on 2022-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f3x_summaries", "0018_f3xsummary_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="f3xsummary",
            name="upload_submission",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="webprint_submission",
            field=models.IntegerField(null=True),
        ),
        migrations.RenameField(
            model_name="f3xsummary",
            old_name="upload_submission",
            new_name="upload_submission_old",
        ),
        migrations.RenameField(
            model_name="f3xsummary",
            old_name="webprint_submission",
            new_name="webprint_submission_old",
        ),
    ]
