# Generated by Django 5.2.1 on 2025-08-11 16:15

import django.db.models.deletion
from fecfiler.imports.models import ImportStatus
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committee_accounts', '0007_alter_committeeaccount_members'),
        ('reports', '00019_form24_name_fix')
    ]

    operations = [
        migrations.CreateModel(
            name='Imports',
            fields=[
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dot_fec_file', models.TextField(blank=True, null=True)),
                ('preprocessed_json', models.JSONField(blank=True, null=True)),
                ('report', models.TextField(null=True, blank=True)),
                ('report_type', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, default=ImportStatus.UPLOADING.value, null=True)),
                ('coverage_from_date', models.DateField(null=True, blank=True)),
                ('coverage_through_date', models.DateField(null=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('committee_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='committee_accounts.committeeaccount')),
            ],
            options={
                'db_table': 'imports',
            },
        ),
    ]
