# Generated by Django 5.2.1 on 2025-08-12 04:43

import fecfiler.imports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imports',
            name='status',
            field=models.TextField(blank=True, default=fecfiler.imports.models.ImportStatus['UPLOADING'], null=True),
        ),
    ]
