# Generated by Django 4.2.7 on 2024-01-02 20:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("committee_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("COM", "Committee"),
                            ("ORG", "Organization"),
                            ("IND", "Individual"),
                            ("CAN", "Candidate"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("candidate_id", models.TextField(blank=True, null=True)),
                ("committee_id", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("last_name", models.TextField(blank=True, null=True)),
                ("first_name", models.TextField(blank=True, null=True)),
                ("middle_name", models.TextField(blank=True, null=True)),
                ("prefix", models.TextField(blank=True, null=True)),
                ("suffix", models.TextField(blank=True, null=True)),
                ("street_1", models.TextField(null=True)),
                ("street_2", models.TextField(blank=True, null=True)),
                ("city", models.TextField(null=True)),
                ("state", models.TextField(null=True)),
                ("zip", models.TextField(null=True)),
                ("employer", models.TextField(blank=True, null=True)),
                ("occupation", models.TextField(blank=True, null=True)),
                (
                    "candidate_office",
                    models.CharField(
                        blank=True,
                        choices=[("H", "House"), ("S", "Senate"), ("P", "Presidential")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("candidate_state", models.TextField(blank=True, null=True)),
                ("candidate_district", models.TextField(blank=True, null=True)),
                ("telephone", models.TextField(blank=True, null=True)),
                ("country", models.TextField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "committee_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="committee_accounts.committeeaccount",
                    ),
                ),
            ],
            options={
                "db_table": "contacts",
            },
        ),
    ]
