# Generated by Django 3.2.12 on 2022-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="state",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="street_1",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.CharField(
                choices=[
                    ("Committee", "Committee"),
                    ("Organization", "Organization"),
                    ("Individual", "Individual"),
                    ("Candidate", "Candidate"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="zip",
            field=models.TextField(null=True),
        ),
    ]
