# Generated by Django 3.2.12 on 2022-09-15 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_committee_uuid_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='uuid',
        ),
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
