# Generated by Django 5.2.17 on 2026-09-22 18:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("committee_accounts", "0011_committeeaccount_candidate_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "office",
                    models.CharField(
                        choices=[
                            ("House", "House"),
                            ("Presidential", "Presidential"),
                            ("Senate", "Senate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "election_type",
                    models.CharField(
                        choices=[("General", "General"), ("Special", "Special")],
                        max_length=20,
                    ),
                ),
                (
                    "election_year",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Election year must be a 4-digit year (YYYY).",
                                regex="^\\d{4}$",
                            )
                        ],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "committee_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="committee_accounts.committeeaccount",
                    ),
                ),
            ],
            options={
                "db_table": "election_cycles",
                "ordering": ["-election_year", "-start_date"],
            },
        ),
    ]
