# Generated by Django 5.2.17 on 2026-10-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_cycles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electioncycle",
            name="office",
            field=models.CharField(
                choices=[("House", "House"), ("Senate", "Senate")], max_length=20
            ),
        ),
    ]
