---
defaults: &defaults
  instances: 1
  stack: cflinuxfs4
  buildpacks:
    - python_buildpack
  memory: 1G
  services:
    - fecfile-api-rds
    - fecfile-api-s3
    - fecfile-api-redis
    - fecfile-api-creds-stage
  env:
    DISABLE_COLLECTSTATIC: 1
    DJANGO_SETTINGS_MODULE: fecfiler.settings.production
    FFAPI_TIMEOUT_COOKIE_NAME: ffapi_timeout_stage
    FFAPI_COOKIE_DOMAIN: fecfile.fec.gov
    LOGIN_REDIRECT_CLIENT_URL: https://stage.fecfile.fec.gov
    LOGIN_REDIRECT_SERVER_URL: https://stage-api.fecfile.fec.gov/api/v1/oidc/login-redirect
    LOGOUT_REDIRECT_URL: https://stage-api.fecfile.fec.gov/api/v1/oidc/logout-redirect
    MOCK_OIDC_PROVIDER: False
    OIDC_OP_AUTODISCOVER_ENDPOINT: https://idp.int.identitysandbox.gov/.well-known/openid-configuration
    PRODUCTION_OPEN_FEC_API: https://api.open.fec.gov/v1/
    STAGE_OPEN_FEC_API: https://api-stage.open.fec.gov/v1/
    EFO_FILING_API: https://efoservices.stage.efo.fec.gov
    FEC_AGENCY_ID: FEC
    SESSION_COOKIE_AGE: 3600 # Value in seconds (1 hour)
    BP_PIP_VERSION: latest
    LOG_FORMAT: KEY_VALUE
    MOCK_EFO_FILING: False
    SYSTEM_STATUS_CACHE_AGE: 60
    INITIAL_POLLING_INTERVAL: 10
    INITIAL_POLLING_DURATION: 900
    SECONDARY_POLLING_INTERVAL: 3600
    SECONDARY_POLLING_DURATION: 86400
    # ---- FEATURE FLAGS ----
    FLAG__COMMITTEE_DATA_SOURCE: TEST # Values are TEST and PRODUCTION
    ENABLE_RESTRICTED_COMMANDS: True
    FEC_FORMAT_VERSION: 8.5

applications:
  - name: fecfile-web-api
    <<: *defaults
    instances: 2
    routes:
      - route: fecfile-web-api-stage.apps.internal
    command: bin/run-api.sh
    memory: 2G
  - name: fecfile-web-services
    <<: *defaults
    instances: 2
    no-route: true
    health-check-type: process
    command: bin/run-celery-worker.sh
  - name: fecfile-api-migrator
    <<: *defaults
    command: bin/run-api.sh
    memory: 2G
    no-route: true
  - name: fecfile-scheduler
    <<: *defaults
    no-route: true
    health-check-type: process
    command: bin/run-scheduler.sh
