---
applications:
  - name: fecfile-api-migrator
    instances: 1
    stack: cflinuxfs4
    buildpacks:
      - python_buildpack
    command: bin/run-api.sh
    memory: 2G
    services:
      - fecfile-api-rds
      - fecfile-api-s3
      - fecfile-api-redis
      - fecfile-api-creds-dev
