---
defaults: &defaults
  instances: 1
  stack: cflinuxfs4
  buildpacks:
    - python_buildpack
  memory: 1G
  services:
    - load-fecfile-api-rds
    - load-fecfile-api-s3
    - load-fecfile-api-redis
    - fecfile-api-creds-dev # Can use dev's creds
  env:
    DISABLE_COLLECTSTATIC: 1
    DJANGO_SETTINGS_MODULE: fecfiler.settings.production
    FFAPI_TIMEOUT_COOKIE_NAME: ffapi_timeout_dev
    FFAPI_COOKIE_DOMAIN: app.cloud.gov
    LOGIN_REDIRECT_CLIENT_URL: https://dev.fecfile.fec.gov
    LOGIN_REDIRECT_SERVER_URL: https://dev-api.fecfile.fec.gov/api/v1/oidc/login-redirect
    LOGOUT_REDIRECT_URL: https://dev-api.fecfile.fec.gov/api/v1/oidc/logout-redirect
    MOCK_OIDC_PROVIDER: False
    OIDC_OP_AUTODISCOVER_ENDPOINT: https://idp.int.identitysandbox.gov/.well-known/openid-configuration
    PRODUCTION_OPEN_FEC_API: https://api.open.fec.gov/v1/
    STAGE_OPEN_FEC_API: https://api-stage.open.fec.gov/v1/
    FEC_AGENCY_ID: FEC
    SESSION_COOKIE_AGE: 3600 # Value in seconds (1 hour)
    BP_PIP_VERSION: latest
    LOG_FORMAT: KEY_VALUE
    MOCK_EFO_FILING: True
    SYSTEM_STATUS_CACHE_AGE: 60
    INITIAL_POLLING_INTERVAL: 10
    INITIAL_POLLING_DURATION: 900
    SECONDARY_POLLING_INTERVAL: 3600
    SECONDARY_POLLING_DURATION: 86400
    # ---- FEATURE FLAGS ----
    FLAG__COMMITTEE_DATA_SOURCE: TEST # Values are PRODUCTION, TEST, MOCKED
    ENABLE_RESTRICTED_COMMANDS: True
    FEC_FORMAT_VERSION: 8.5
    MOCK_OIDC_PROVIDER: True
    OIDC_OP_AUTODISCOVER_ENDPOINT: https://load-dev-api.app.cloud.gov/api/v1/mock_oidc_provider/.well-known/openid-configuration

applications:
  - name: load-fecfile-web-api
    <<: *defaults
    instances: 4
    routes:
      - route: load-fecfile-web-api-dev.apps.internal
    command: bin/run-api.sh
    memory: 2G
  - name: load-fecfile-web-services
    <<: *defaults
    instances: 4
    no-route: true
    health-check-type: process
    command: bin/run-celery-worker.sh
  - name: load-fecfile-api-migrator
    <<: *defaults
    command: bin/run-api.sh
    memory: 2G
    no-route: true
  - name: load-fecfile-scheduler
    <<: *defaults
    no-route: true
    health-check-type: process
    command: bin/run-scheduler.sh
