---
applications:
  - name: fecfile-web-api
    instances: 2
    routes:
      - route: fecfile-web-api-dev.app.cloud.gov
    stack: cflinuxfs4
    buildpacks:
      - python_buildpack
    command: cd django-backend && ./manage.py migrate --no-input --traceback --verbosity 3 && python manage.py create_committee_views && exec gunicorn --bind 0.0.0.0:8080 fecfiler.wsgi -w 9
    memory: 2G
    services:
      - fecfile-api-rds
      - fecfile-api-s3
      - fecfile-api-redis
      - fecfile-api-creds-dev
    env:
      DISABLE_COLLECTSTATIC: 1
      DJANGO_SETTINGS_MODULE: fecfiler.settings.production
      CORS_ALLOWED_ORIGINS: https://fecfile-web-app-dev.app.cloud.gov
      CSRF_TRUSTED_ORIGINS: https://fecfile-web-app-dev.app.cloud.gov
      FFAPI_COOKIE_DOMAIN: app.cloud.gov
      FRONTEND_URL: fecfile-web-app-dev.app.cloud.gov
      LOGIN_REDIRECT_CLIENT_URL: https://fecfile-web-app-dev.app.cloud.gov
      LOGIN_REDIRECT_SERVER_URL: https://fecfile-web-api-dev.app.cloud.gov/api/v1/auth/login-redirect
      LOGOUT_REDIRECT_URL: https://fecfile-web-api-dev.app.cloud.gov/api/v1/auth/logout-redirect
      SESSION_COOKIE_AGE: 64800
      LOG_FORMAT: KEY_VALUE
      MOCK_OPENFEC: REDIS
