---
applications:
  - name: fecfile-web-api
    instances: 2
    routes:
      - route: fecfile-web-api-stage.apps.internal
    stack: cflinuxfs4
    buildpacks:
      - python_buildpack
    command: bin/run-api.sh
    memory: 2G
    services:
      - fecfile-api-rds
      - fecfile-api-s3
      - fecfile-api-redis
      - fecfile-api-creds-stage
    env:
      DISABLE_COLLECTSTATIC: 1
      DJANGO_SETTINGS_MODULE: fecfiler.settings.production
      CSRF_TRUSTED_ORIGINS: https://fecfile-web-app-stage.app.cloud.gov
      FFAPI_COOKIE_DOMAIN: app.cloud.gov
      LOGIN_REDIRECT_CLIENT_URL: https://fecfile-web-app-stage.app.cloud.gov
      LOGIN_REDIRECT_SERVER_URL: https://fecfile-web-api-stage.app.cloud.gov/api/v1/auth/login-redirect
      LOGOUT_REDIRECT_URL: https://fecfile-web-api-stage.app.cloud.gov/api/v1/auth/logout-redirect
      FEC_API: https://api.open.fec.gov/v1/
      SESSION_COOKIE_AGE: 64800
      BP_PIP_VERSION: latest
      LOG_FORMAT: KEY_VALUE
      MOCK_OPENFEC: REDIS
