---
applications:
  - name: fecfile-web-api
    instances: 2
    routes:
      - route: fecfile-web-api-dev.apps.internal
    stack: cflinuxfs4
    buildpacks:
      - python_buildpack
    command: bin/run-api.sh
    memory: 2G
    services:
      - fecfile-api-rds
      - fecfile-api-s3
      - fecfile-api-redis
      - fecfile-api-creds-dev
    env:
      DISABLE_COLLECTSTATIC: 1
      DJANGO_SETTINGS_MODULE: fecfiler.settings.production
      FFAPI_COOKIE_DOMAIN: fecfile.fec.gov
      LOGIN_REDIRECT_CLIENT_URL: https://dev.fecfile.fec.gov
      LOGIN_REDIRECT_SERVER_URL: https://dev-api.fecfile.fec.gov/api/v1/oidc/login-redirect
      LOGOUT_REDIRECT_URL: https://dev-api.fecfile.fec.gov/api/v1/oidc/logout-redirect
      FEC_API_PROD: https://api.open.fec.gov/v1/
      FEC_API_TEST: https://api-stage.open.fec.gov/v1/
      SESSION_COOKIE_AGE: 64800
      BP_PIP_VERSION: latest
      LOG_FORMAT: KEY_VALUE
      SYSTEM_STATUS_CACHE_AGE: 60
      # ---- FEATURE FLAGS ----
      FLAG__COMMITTEE_DATA_SOURCE: TEST # Values are PRODUCTION, TEST, and REDIS, defaults to TEST
