---
applications:
  - name: fecfile-web-services-sched
    instances: 1
    stack: cflinuxfs4
    buildpacks:
      - python_buildpack
    memory: 500M
    no-route: true
    health-check-type: process
    command: bin/run-celery-beat.sh
    services:
      - fecfile-api-rds
      - fecfile-api-s3
      - fecfile-api-redis
      - fecfile-api-creds-dev
    env:
      DISABLE_COLLECTSTATIC: 1
      DJANGO_SETTINGS_MODULE: fecfiler.settings.production
