---
applications:
  - name: fecfile-web-services-test
    instances: 2
    stack: cflinuxfs4
    buildpacks:
      - python_buildpack
    memory: 1G
    no-route: true
    health-check-type: process
    command: bin/run-celery-worker.sh
    services:
      - fecfile-api-rds
      - fecfile-api-s3
      - fecfile-api-redis
      - fecfile-api-creds-dev
    env:
      DISABLE_COLLECTSTATIC: 1
      DJANGO_SETTINGS_MODULE: fecfiler.settings.production
      FEC_AGENCY_ID: FEC
      FEC_FILING_API: https://efoservices.stage.efo.fec.gov
      LOG_FORMAT: KEY_VALUE
