export class LoanModel {
  cmte_id: string ;
  report_id: number;
  line_number: string;
  transaction_type: string;
  transaction_type_identifier: string;
  transaction_id: string
  entity_id: string;
  name: string;
  entity_name: string;
  lastName: string;
  firstName: string;
  middleName: string;
  suffix: string;
  prefix: string;
  street1: string;
  street2: string;
  city: string;
  state: string;
  zip: string;
  phoneNumber: string;
  entity_type: string;
  election_code: string;
  election_other_description: string;
  loan_amount_original: number;
  loan_payment_to_date: number;
  loan_balance: number;
  loan_incurred_date: string;
  loan_due_date: string;
  loan_intrest_rate: number;
  is_loan_secured: string;
  is_personal_funds: string;
  lender_cmte_id: string;
  lender_cand_id: string;
  lender_cand_last_name: string;
  lender_cand_first_name: string;
  lender_cand_middle_name: string;
  lender_cand_prefix: string;
  lender_cand_suffix: string;
  lender_cand_office: string;
  lender_cand_state: string;
  lender_cand_district: number;
  memo_code: string;
  memo_text: string;
  delete_ind: string;
  selected: boolean;
  payments: any[];
  child: any[];
  hasC1: any;
  hasC2: any;
  toggleChild: boolean;
  togglePayments: boolean;
    constructor(loan: any) {
        this.cmte_id = loan.cmte_id ? loan.cmte_id : '';
        this.report_id = loan.report_id ? loan.report_id : 0;
        this.line_number = loan.line_number ? loan.line_number : 0;
        this.transaction_type = loan.transaction_type ? loan.transaction_type : '';
        this.transaction_id = loan.transaction_id ? loan.transaction_id : '';
        this.transaction_type_identifier = loan.transaction_type_identifier ? loan.transaction_type_identifier : '';
        this.entity_id = loan.entity_id ? loan.entity_id : '';
        this.name = loan.name ? loan.name : '';
        this.entity_name = loan.entity_name ? loan.entity_name : '';
        this.lastName = loan.last_Name ? loan.last_Name : '';
        this.firstName = loan.first_name ? loan.first_name : '';
        this.middleName = loan.middle_ame ? loan.middle_name : '';
        this.suffix = loan.suffix ? loan.suffix : '';
        this.prefix = loan.prefix ? loan.prefix : '';
        this.street1 = loan.street1 ? loan.street1 : '';
        this.street2 = loan.street2 ? loan.street2 : '';
        this.city = loan.city ? loan.city : '';
        this.state = loan.state ? loan.state : '';
        this.zip = loan.zip ? loan.zip : '';
        this.phoneNumber = loan.phoneNumber ? loan.phoneNumber : '';
        this.election_code = loan.election_code ? loan.election_code : '';
        this.election_other_description = loan.election_other_description ? loan.election_other_description : '';
        this.loan_amount_original = loan.loan_amount_original ? loan.loan_amount_original : 0;
        this.loan_payment_to_date = loan.loan_payment_to_date ? loan.loan_payment_to_date : 0;
        this.loan_balance = loan.loan_balance ? loan.loan_balance : 0;
        this.loan_incurred_date = loan.loan_incurred_date ? loan.loan_incurred_date : '';
        this.loan_due_date = loan.loan_due_date ? loan.loan_due_date : '';
        this.loan_intrest_rate = loan.loan_intrest_rate ? loan.loan_intrest_rate : 0;
        this.lender_cand_last_name = loan.lender_cand_last_name ? loan.lender_cand_last_name : '';
        this.lender_cand_first_name = loan.lender_cand_first_name ? loan.lender_cand_first_name : '';
        this.lender_cand_middle_name = loan.lender_cand_middle_name ? loan.lender_cand_middle_name : '';
        this.lender_cand_prefix = loan.lender_cand_prefix ? loan.lender_cand_prefix : '';
        this.lender_cand_suffix = loan.lender_cand_suffix ? loan.lender_cand_suffix : '';
        this.lender_cand_office = loan.lender_cand_office ? loan.lender_cand_office : '';
        this.lender_cand_state = loan.lender_cand_state ? loan.lender_cand_state : '';
        this.lender_cand_district = loan.lender_cand_district ? loan.lender_cand_district : '';
        this.memo_code = loan.memo_code ? loan.memo_code : '';
        this.memo_text = loan.memo_text ? loan.memo_text : '';
        this.delete_ind = loan.delete_ind ? loan.delete_ind : '';
        this.selected = loan.selected;
        this.child = loan.child;
        this.payments = loan.payments;
        this.hasC1 = loan.hasC1;
        this.hasC2 = loan.hasC2;
        this.toggleChild = loan.toggleChild || false;
        this.togglePayments = loan.togglePayments || false;

    }
}
