# Generated by Django 3.2.11 on 2022-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filing_Notification',
            fields=[
                ('notification_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cmte_id', models.CharField(max_length=9)),
                ('notification_type', models.CharField(max_length=100)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('message_subject', models.CharField(max_length=500)),
                ('message_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='My_Forms_View',
            fields=[
                ('cmte_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=25)),
                ('form_type', models.CharField(max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('form_description', models.CharField(blank=True, max_length=300, null=True)),
                ('form_info', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cmte_Report_Types_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmte_id', models.CharField(max_length=9)),
                ('filing_freq', models.CharField(blank=True, max_length=1, null=True)),
                ('form_type', models.CharField(max_length=10)),
                ('report_type', models.CharField(max_length=10)),
                ('rpt_type_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('regular_special_report_ind', models.CharField(blank=True, max_length=3, null=True)),
                ('rpt_type_info', models.CharField(blank=True, max_length=200, null=True)),
                ('rpt_type_order', models.IntegerField(blank=True, null=True)),
                ('cvg_start_date', models.DateField(blank=True, null=True)),
                ('cvg_end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('cmte_id', 'form_type', 'report_type')},
            },
        ),
    ]
