# Generated by Django 3.2.12 on 2022-05-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uuid',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
