# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
