# Generated by Django 4.2.7 on 2024-01-30 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='security_consent_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='security consent date'),
        ),
    ]
