export enum FilterTypes {
  keyword = 'keyword',
  category = 'category',
  semiAnnualAmount = 'semiAnnualAmount',
  amount = 'amount',
  aggregateAmount = 'aggregateAmount',
  date = 'date',
  deletedDate = 'deletedDate',
  state = 'state',
  memoCode = 'memoCode',
  itemizations = 'itemizations',
  electionCodes = 'electionCodes',
  electionYear = 'electionYear',
  loanAmount = 'loanAmount',
  loanClosingBalance = 'loanClosingBalance',
  schedule = 'schedule',
  entityId = 'entityId',
  debtBeginningBalance = "debtBeginningBalance", 
  reportType = "reportType"
}
