over_two_hundred_types = [
    "INDEPENDENT_EXPENDITURE",
    "INDEPENDENT_EXPENDITURE_VOID",
    "INDEPENDENT_EXPENDITURE_CREDIT_CARD_PAYMENT",
    "INDEPENDENT_EXPENDITURE_PAYMENT_TO_PAYROLL",
    "INDEPENDENT_EXPENDITURE_STAFF_REIMBURSEMENT",
    "INDEPENDENT_EXPENDITURE_CREDIT_CARD_PAYMENT_MEMO",
    "INDEPENDENT_EXPENDITURE_PAYMENT_TO_PAYROLL_MEMO",
    "INDEPENDENT_EXPENDITURE_STAFF_REIMBURSEMENT_MEMO",
]
