
from django.db import models

class SATransaction(models.Model):
    """Generated model from json schema"""
    FORM_TYPE = models.TextField(null=False, blank=False)
    FILER_COMMITTEE_ID_NUMBER = models.TextField(null=False, blank=False)
    TRANSACTION_ID = models.TextField(null=False, blank=False)
    BACK_REFERENCE_TRAN_ID_NUMBER = models.TextField(null=True, blank=True)
    BACK_REFERENCE_SCHED_NAME = models.TextField(null=True, blank=True)
    ENTITY_TYPE = models.TextField(null=False, blank=False)
    CONTRIBUTOR_ORGANIZATION_NAME = models.TextField(null=False, blank=False)
    CONTRIBUTOR_LAST_NAME = models.TextField(null=False, blank=False)
    CONTRIBUTOR_FIRST_NAME = models.TextField(null=False, blank=False)
    CONTRIBUTOR_MIDDLE_NAME = models.TextField(null=True, blank=True)
    CONTRIBUTOR_PREFIX = models.TextField(null=True, blank=True)
    CONTRIBUTOR_SUFFIX = models.TextField(null=True, blank=True)
    CONTRIBUTOR_STREET_1 = models.TextField(null=True, blank=True)
    CONTRIBUTOR_STREET_2 = models.TextField(null=True, blank=True)
    CONTRIBUTOR_CITY = models.TextField(null=True, blank=True)
    CONTRIBUTOR_STATE = models.TextField(null=True, blank=True)
    CONTRIBUTOR_ZIP = models.TextField(null=True, blank=True)
    ELECTION_CODE = models.TextField(null=True, blank=True)
    ELECTION_OTHER_DESCRIPTION = models.TextField(null=True, blank=True)
    CONTRIBUTION_AMOUNT_F3L_Bundled = models.IntegerField(null=True)
    CONTRIBUTION_AGGREGATE_F3L_Semi_annual_Bundled = models.IntegerField(null=True)
    CONTRIBUTION_PURPOSE_DESCRIP = models.TextField(null=True, blank=True)
    CONTRIBUTOR_EMPLOYER = models.TextField(null=True, blank=True)
    CONTRIBUTOR_OCCUPATION = models.TextField(null=True, blank=True)
    DONOR_COMMITTEE_FEC_ID = models.TextField(null=True, blank=True)
    DONOR_COMMITTEE_NAME = models.TextField(null=True, blank=True)
    DONOR_CANDIDATE_FEC_ID = models.TextField(null=True, blank=True)
    DONOR_CANDIDATE_LAST_NAME = models.TextField(null=True, blank=True)
    DONOR_CANDIDATE_FIRST_NAME = models.TextField(null=True, blank=True)
    DONOR_CANDIDATE_MIDDLE_NAME = models.TextField(null=True, blank=True)
    DONOR_CANDIDATE_PREFIX = models.TextField(null=True, blank=True)
    DONOR_CANDIDATE_SUFFIX = models.TextField(null=True, blank=True)
    DONOR_CANDIDATE_OFFICE = models.TextField(null=True, blank=True)
    DONOR_CANDIDATE_STATE = models.TextField(null=True, blank=True)
    CONDUIT_NAME = models.TextField(null=True, blank=True)
    CONDUIT_STREET1 = models.TextField(null=True, blank=True)
    CONDUIT_STREET2 = models.TextField(null=True, blank=True)
    CONDUIT_CITY = models.TextField(null=True, blank=True)
    CONDUIT_STATE = models.TextField(null=True, blank=True)
    CONDUIT_ZIP = models.TextField(null=True, blank=True)
    MEMO_CODE = models.TextField(null=True, blank=True)
    MEMO_TEXT_DESCRIPTION = models.TextField(null=True, blank=True)
    Reference_to_SI_or_SL_system_code_that_identifies_the_Account = models.TextField(null=True, blank=True)
    TRANSACTION_TYPE_IDENTIFIER = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'sa_transactions'
