FROM postgres:12

ENV POSTGRES_USER=postgres
ENV POSTGRES_NAME=postgres
ENV POSTGRES_PASSWORD=postgres
ARG ENCRYPTION_PASSWORD

RUN echo 'E2E Dockerfile'
# Load scripts to run at container initialization. They are run in alphabetical order.
 COPY e2e-test-db.sql /docker-entrypoint-initdb.d

EXPOSE 5432
