export class TransactionModel {
  type: string;
  entityId: string;
  entityType: string;
  apiCall: string;
  scheduleType: string;
  transactionId: string;
  backRefTransactionId: string;
  transactionTypeIdentifier: string;
  name: string;
  street: string;
  street2: string;
  city: string;
  state: string;
  zip: string;
  date: Date;
  amount: number;
  deletedDate: Date;
  aggregate: number;
  purposeDescription: string;
  contributorEmployer: string;
  contributorOccupation: string;
  memoCode: string;
  memoText: string;
  selected: boolean;
  itemized: string;
  reportstatus: string;
  toggleChild: boolean;
  child: TransactionModel[] = [];
  cloned: boolean;
  electionCode: any;
  electionYear: any;
  loanAmount: any;
  loanBalance: any;
  loanBeginningBalance: any;
  loanClosingBalance: any;
  loanDueDate: any;
  loanIncurredAmt: any;
  loanIncurredDate: any;
  loanPaymentAmt: any;
  loanPaymentToDate: any;
  isReattribution = false;
  reattribution_id:string;
  isreattributable = false;
  isRedesignation = false;
  redesignation_id:string;
  isredesignatable = false;
  reportType: any;
  activityEventType: any;
  activityEventIdentifier: any;
  fedShareAmount: any;
  nonfedShareAmount: any;
  levinShare: any;
  purpose: any;
  reportId: any;
  scrollDebtPaymentButtonIntoView: boolean;
  iseditable: boolean;
  isTrashable:boolean;
  disbursementDate:Date;
  disseminationDate:Date;
  candLastName: string;
  candFirstName: string;
  candMiddleName: string;
  candPrefix: string;
  candSuffix: string;
  candFECId: string;
  benificiaryCandId: string;
  candOffice:string;
  candOfficeState:string;
  candOfficeDistrict:string;
  candElectionCode:string;
  candElectionYear:string;
  candSupportOpposeFlag:string;
  candElectionOtherDesc: string;
  originalAmount: any;

  //used by sched f core child trx
  coordinatedExpInd: string;
  designatingCmteId: string;
  designatingCmteName: string;
  subordinateCmteId: string;
  subordinateCmteName: string;
  subordinateCmteStreet_1: string;
  subordinateCmteStreet_2: string;
  subordinateCmteCity: string;
  subordinateCmteState: string;
  subordinateCmteZip: string;

  aggregation_ind: string;


  constructor(transaction: any) {
    this.type = transaction.type ? transaction.type : '';
    this.entityId = transaction.entityId ? transaction.entityId : '';
    this.entityType = transaction.entityType ? transaction.entityType : '';
    this.apiCall = transaction.apiCall ? transaction.apiCall : '';
    this.scheduleType = transaction.scheduleType ? transaction.scheduleType : '';
    this.transactionId = transaction.transactionId ? transaction.transactionId : '';
    this.backRefTransactionId = transaction.backRefTransactionId ? transaction.backRefTransactionId : '';
    this.transactionTypeIdentifier = transaction.transactionTypeIdentifier ? transaction.transactionTypeIdentifier : '';
    this.name = transaction.name ? transaction.name : '';
    this.street = transaction.street ? transaction.street : '';
    this.street2 = transaction.street2 ? transaction.street2 : '';
    this.city = transaction.city ? transaction.city : '';
    this.state = transaction.state ? transaction.state : '';
    this.zip = transaction.zip ? transaction.zip : '';
    this.date = transaction.date ? transaction.date : null;
    this.amount = transaction.amount ? transaction.amount : null;
    this.deletedDate = transaction.deletedDate ? transaction.deletedDate : null;
    this.disbursementDate = transaction.disbursementDate ? transaction.disbursementDate : null;
    this.disseminationDate = transaction.disseminationDate ? transaction.disseminationDate : null;
    this.aggregate = transaction.aggregate ? transaction.aggregate : null;
    this.purposeDescription = transaction.purposeDescription ? transaction.purposeDescription : '';
    this.contributorEmployer = transaction.contributorEmployer ? transaction.contributorEmployer : '';
    this.contributorOccupation = transaction.contributorOccupation ? transaction.contributorOccupation : '';
    this.memoCode = transaction.memoCode ? transaction.memoCode : '';
    this.memoText = transaction.memoText ? transaction.memoText : '';
    this.electionCode = transaction.electionCode ? transaction.electionCode : '';
    this.electionYear = transaction.electionYear ? transaction.electionYear : '';
    this.loanAmount = transaction.loanAmount ? transaction.loanAmount : '';
    this.loanBalance = transaction.loanBalance ? transaction.loanBalance : '';
    this.loanBeginningBalance = transaction.loanBeginningBalance ? transaction.loanBeginningBalance : '';
    this.loanClosingBalance = transaction.loanClosingBalance ? transaction.loanClosingBalance : '';
    this.loanDueDate = transaction.loanDueDate ? transaction.loanDueDate : '';
    this.loanIncurredAmt = transaction.loanIncurredAmt ? transaction.loanIncurredAmt : '';
    this.loanIncurredDate = transaction.loanIncurredDate ? transaction.loanIncurredDate : '';
    this.loanPaymentAmt = transaction.loanPaymentAmt ? transaction.loanPaymentAmt : '';
    this.loanPaymentToDate = transaction.loanPaymentToDate ? transaction.loanPaymentToDate : '';
    this.reportType = transaction.reportType ? transaction.reportType : '';
    this.selected = transaction.selected;
    this.itemized = transaction.itemized;
    this.reportstatus = transaction.reportstatus;
    this.toggleChild = transaction.toggleChild;
    this.child = transaction.child;
    this.activityEventType = transaction.activityEventType;
    this.activityEventIdentifier = transaction.activityEventIdentifier;
    this.fedShareAmount = transaction.fedShareAmount;
    this.nonfedShareAmount = transaction.nonfedShareAmount;
    this.levinShare = transaction.levinShare;
    this.purpose = transaction.purpose;
    this.scrollDebtPaymentButtonIntoView = transaction.scrollDebtPaymentButtonIntoView ? transaction.scrollDebtPaymentButtonIntoView : false;
    this.reportId = transaction.reportId;
    this.candLastName = transaction.candLastName;
    this.candFirstName = transaction.candFirstName;
    this.candMiddleName = transaction.candMiddleName;
    this.candPrefix = transaction.candPrefix;
    this.candSuffix = transaction.candSuffix;
    this.candFECId = transaction.candFECId;
    this.benificiaryCandId = transaction.benificiaryCandId;
    this.candOffice = transaction.candOffice;
    this.candOfficeState = transaction.candOfficeState;
    this.candOfficeDistrict = transaction.candOfficeDistrict;
    this.candElectionCode = transaction.candElectionCode;
    this.candElectionYear = transaction.candElectionYear;
    this.candElectionOtherDesc = transaction.candElectionOtherDesc;
    this.candSupportOpposeFlag = transaction.candSupportOpposeFlag;
    this.isReattribution = transaction.isReattribution;
    this.isreattributable = transaction.isreattributable;
    this.reattribution_id = transaction.reattribution_id;
    this.isredesignatable = transaction.isredesignatable;
    this.isRedesignation = transaction.isRedesignation;
    this.redesignation_id = transaction.redesignation_id;
    this.originalAmount = transaction.originalAmount;
    this.aggregation_ind = transaction.aggregation_ind;

  }
}
