# Generated by Django 3.2.11 on 2022-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedL',
            fields=[
                ('cmte_id', models.CharField(max_length=9)),
                ('report_id', models.BigIntegerField()),
                ('transaction_type_identifier', models.CharField(blank=True, max_length=12, null=True)),
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('record_id', models.CharField(max_length=90)),
                ('account_name', models.CharField(max_length=20)),
                ('cvg_from_date', models.DateField(blank=True, null=True)),
                ('cvg_end_date', models.DateField(blank=True, null=True)),
                ('item_receipts', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unitem_receipts', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ttl_receipts', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_receipts', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_receipts', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('voter_reg_disb_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('voter_id_disb_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gotv_disb_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('generic_campaign_disb_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_disb_sub', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_disb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_disb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coh_bop', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('receipts', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disbursements', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coh_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('item_receipts_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unitem_receipts_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_reciepts_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_receipts_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_receipts_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('voter_reg_disb_amount_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('voter_id_disb_amount_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gotv_disb_amount_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('generic_campaign_disb_amount_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_disb_sub_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_disb_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_disb_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coh_coy', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('receipts_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sub_total_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disbursements_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coh_cop_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delete_ind', models.CharField(blank=True, max_length=1, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sched_l',
                'managed': False,
            },
        ),
    ]
