# Generated by Django 4.2.11 on 2024-10-22 03:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="F3xLine6aOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("year", models.TextField(unique=True)),
                ("cash_on_hand", models.DecimalField(decimal_places=2, max_digits=11)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "f3x_line6a_overrides",
            },
        ),
    ]
