# Generated by Django 5.1.1 on 2024-10-21 23:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="F3xLine6aOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "L6a_cash_on_hand_jan_1_ytd",
                    models.DecimalField(decimal_places=2, max_digits=11),
                ),
                ("L6a_year_for_above_ytd", models.TextField(unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "f3x_line6a_overrides",
            },
        ),
    ]
