# Generated by Django 3.2.11 on 2022-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedH3',
            fields=[
                ('cmte_id', models.CharField(max_length=9)),
                ('report_id', models.BigIntegerField()),
                ('transaction_type_identifier', models.CharField(blank=True, max_length=12, null=True)),
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('back_ref_transaction_id', models.CharField(max_length=20)),
                ('back_ref_sched_name', models.CharField(max_length=8)),
                ('account_name', models.CharField(max_length=90)),
                ('activity_event_type', models.CharField(max_length=2)),
                ('activity_event_name', models.CharField(max_length=90)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('total_amount_transferred', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transferred_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('memo_code', models.CharField(blank=True, max_length=1, null=True)),
                ('memo_text', models.CharField(blank=True, max_length=90, null=True)),
                ('delete_ind', models.CharField(blank=True, max_length=1, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sched_h3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchedH4',
            fields=[
                ('cmte_id', models.CharField(max_length=9)),
                ('report_id', models.BigIntegerField()),
                ('transaction_type_identifier', models.CharField(blank=True, max_length=12, null=True)),
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('back_ref_transaction_id', models.CharField(max_length=20)),
                ('back_ref_sched_name', models.CharField(max_length=8)),
                ('payee_entity_id', models.CharField(max_length=20)),
                ('activity_event_identifier', models.CharField(max_length=90)),
                ('expenditure_date', models.DateField(blank=True, null=True)),
                ('fed_share_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('non_fed_share_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activity_event_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purpose', models.CharField(max_length=100)),
                ('category_code', models.CharField(max_length=2)),
                ('activity_event_type', models.CharField(max_length=2)),
                ('memo_code', models.CharField(blank=True, max_length=1, null=True)),
                ('memo_text', models.CharField(blank=True, max_length=90, null=True)),
                ('delete_ind', models.CharField(blank=True, max_length=1, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sched_h4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchedH5',
            fields=[
                ('cmte_id', models.CharField(max_length=9)),
                ('report_id', models.BigIntegerField()),
                ('transaction_type_identifier', models.CharField(blank=True, max_length=12, null=True)),
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=90)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('total_amount_transferred', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('voter_registration_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('voter_id_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gotv_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('generic_campaign_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('memo_code', models.CharField(blank=True, max_length=1, null=True)),
                ('memo_text', models.CharField(blank=True, max_length=90, null=True)),
                ('delete_ind', models.CharField(blank=True, max_length=1, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sched_h5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchedH6',
            fields=[
                ('cmte_id', models.CharField(max_length=9)),
                ('report_id', models.BigIntegerField()),
                ('line_number', models.CharField(blank=True, max_length=8, null=True)),
                ('transaction_type_identifier', models.CharField(blank=True, max_length=12, null=True)),
                ('transaction_type', models.CharField(max_length=12)),
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('back_ref_transaction_id', models.CharField(max_length=20)),
                ('back_ref_sched_name', models.CharField(max_length=8)),
                ('entity_id', models.CharField(max_length=20)),
                ('account_event_identifier', models.CharField(max_length=90)),
                ('expenditure_date', models.DateField(blank=True, null=True)),
                ('total_fed_levin_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('federal_share', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('levin_share', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activity_event_total_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expenditure_purpose', models.CharField(max_length=100)),
                ('category_code', models.CharField(max_length=3)),
                ('activity_event_type', models.CharField(max_length=20)),
                ('memo_code', models.CharField(blank=True, max_length=1, null=True)),
                ('memo_text', models.CharField(blank=True, max_length=90, null=True)),
                ('delete_ind', models.CharField(blank=True, max_length=1, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sched_h6',
                'managed': False,
            },
        ),
    ]
