# Generated by Django 4.2.7 on 2024-01-25 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("committee_accounts", "0002_membership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="cmtee_id",
        ),
    ]
