# Generated by Django 4.2.7 on 2024-02-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_cmtee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_consent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
