# Generated by Django 4.2.7 on 2024-02-16 20:43

from django.db import migrations
import fecfiler.user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_security_consent_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', fecfiler.user.managers.UserManager()),
            ],
        ),
    ]
