# Generated by Django 4.2.7 on 2024-03-11 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="security_consent_date",
            new_name="security_consent_exp_date",
        ),
    ]
