# Generated by Django 5.1.3 on 2024-12-31 18:50

from django.db import migrations, models


def a_non_reversible_function(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_old_login_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_field_for_testing',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.RunPython(a_non_reversible_function)
    ]
