# Generated by Django 5.1.4 on 2025-01-08 16:54

from django.db import migrations


def do_nothing(apps, schema_editor):
    print("We're truly doing nothing here")


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_old_login_accounts'),
    ]

    operations = [
        migrations.RunPython(
            do_nothing,
            migrations.RunPython.noop,
        ),
    ]
