# Generated by Django 5.2.2 on 2025-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_old_login_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_consent_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
