# Generated by Django 5.1.4 on 2025-01-15 18:35

from django.db import migrations


def raise_error(apps, schema_editor):
    raise ValueError


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_test_migration'),
    ]

    operations = [
        migrations.RunPython(
            raise_error,
            migrations.RunPython.noop,
        ),
    ]
