# Generated by Django 3.2.12 on 2022-07-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f3x_summaries', '0011_auto_20220609_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotFEC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f3x_summaries.f3xsummary')),
            ],
            options={
                'db_table': 'dot_fecs',
            },
        ),
    ]
