# Generated by Django 5.2.11 on 2026-03-07 03:21

import django.db.migrations.operations.special
from django.db import migrations, models
from django.db.models import F


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# fecfiler.web_services.migrations.0002_uploadsubmission_task_completed_and_more


def set_default_task_completed_times(apps, schema_editor):
    uploads = apps.get_model("web_services", "UploadSubmission")
    web_prints = apps.get_model("web_services", "WebPrintSubmission")

    uploads.objects.all().update(task_completed=F("updated"))
    web_prints.objects.all().update(task_completed=F("updated"))


class Migration(migrations.Migration):

    replaces = [
        ("web_services", "0002_uploadsubmission_task_completed_and_more"),
        ("web_services", "0003_uploadsubmission_fecfile_polling_attempts_and_more"),
    ]

    dependencies = [
        ("web_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsubmission",
            name="task_completed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="webprintsubmission",
            name="task_completed",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            code=set_default_task_completed_times,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="uploadsubmission",
            name="fecfile_polling_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="webprintsubmission",
            name="fecfile_polling_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
