# Generated by Django 3.2.12 on 2022-08-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_services", "0002_uploadsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsubmission",
            name="dot_fec",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="web_services.dotfec",
            ),
        ),
        migrations.AddField(
            model_name="uploadsubmission",
            name="fecfile_error",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="uploadsubmission",
            name="fec_message",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="uploadsubmission",
            name="fec_status",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="uploadsubmission",
            name="fecfile_task_state",
            field=models.CharField(max_length=255),
        ),
    ]
