# Generated by Django 3.2.12 on 2022-08-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0003_auto_20220811_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsubmission',
            name='fec_report_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadsubmission',
            name='fec_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadsubmission',
            name='fec_submission_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
