# Generated by Django 5.0.8 on 2024-09-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_services", "0003_uploadsubmission_fecfile_polling_attempts_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                SECURITY LABEL FOR anon ON COLUMN user_user.first_name IS 'MASKED WITH FUNCTION anon.fake_first_name()';
                SECURITY LABEL FOR anon ON COLUMN user_user.last_name IS 'MASKED WITH FUNCTION anon.fake_last_name()';
                SECURITY LABEL FOR anon ON COLUMN user_user.email IS 'MASKED WITH FUNCTION anon.fake_email()';
            """,
            reverse_sql="""
                -- Define reverse operations to drop the security labels
                SECURITY LABEL FOR anon ON COLUMN user_user.first_name IS NULL;
                SECURITY LABEL FOR anon ON COLUMN user_user.last_name IS NULL;
                SECURITY LABEL FOR anon ON COLUMN user_user.email IS NULL;
                -- Repeat for each column you masked
            """,
        ),
    ]
