# Generated by Danguy 4.7.6 on 2025-06-18 08:30


from django.db import migrations
import time
import structlog

logger = structlog.get_logger(__name__)


def raise_error_during_migration(error_msg):
    """
    Raises an intentional error during the migration process.
    """
    raise Exception(error_msg)


def sleep_during_migration(minutes):
    """
    Sleeps for given number of minutes
    """
    logger.info(f"Sleeping for {minutes} minutes...")
    for minute in range(minutes):
        logger.info(f"Minute: {minute}")
        time.sleep(60)
    logger.info(f"Slept for {minutes} minutes")


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0003_uploadsubmission_fecfile_polling_attempts_and_more'),
    ]

    operations = [
        # migrations.RunPython(raise_error_during_migration("Error at outset.")),
        migrations.RunPython(sleep_during_migration(15)),  # sleep for 15 minutes
        migrations.RunPython(raise_error_during_migration("Intentional error!")),
    ]
