# Generated by Danguy 4.7.6 on 2025-06-18 08:30


from django.db import migrations
import time


def raise_error_during_migration(error_msg):
    """
    Raises an intentional error during the migration process.
    """
    raise Exception(error_msg)


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0003_uploadsubmission_fecfile_polling_attempts_and_more'),
    ]

    operations = [
        # migrations.RunPython(raise_error_during_migration("Error at outset.")),
        # migrations.RunPython(print("about to exec: migrations.RunPython(time.sleep(660))")),
        migrations.RunPython(time.sleep(660)),  # sleep for 11 minutes
        # migrations.RunPython(print("""about to exec: raise_error_during_migration("Intentional error!")""")),
        migrations.RunPython(raise_error_during_migration("Intentional error!")),
    ]
