# Generated by Django 5.2.11 on 2026-03-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0001_initial_squashed_0003_polling_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsubmission',
            name='date_filed',
            field=models.DateTimeField(null=True),
        ),
    ]
