# Generated by Danguy 4.7.6 on 2025-06-18 08:30


from django.db import migrations
import time


def raise_error_during_migration(error_msg):
    """
    Raises an intentional error during the migration process.
    """
    raise Exception(error_msg)


def sleep_for_duration(duration):
    """
    Sleeps for the specified duration in seconds.
    """
    time.sleep(duration)


def sleep_for_3minutes(apps, schema_editor):
    """
    Sleeps for 3 minutes during the migration process.
    This is useful for testing purposes to simulate a long-running migration.
    """
    sleep_for_duration(180)  # Sleep for 3 minutes


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0003_uploadsubmission_fecfile_polling_attempts_and_more'),
    ]

    operations = [
        # migrations.RunPython(raise_error_during_migration("Error at outset.")),
        migrations.RunPython(code=sleep_for_3minutes),  # sleep for 3 minutes
        # migrations.RunPython(raise_error_during_migration("Intentional error!")),
    ]
