# Generated by Django 3.2.12 on 2022-08-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0004_auto_20220811_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsubmission',
            name='report',
        ),
        migrations.AlterField(
            model_name='uploadsubmission',
            name='dot_fec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_services.dotfec'),
        ),
    ]
