# Generated by Django 3.2.12 on 2022-08-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0006_webprintsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='webprintsubmission',
            name='fec_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
