# Generated by Django 3.2.12 on 2022-08-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0007_webprintsubmission_fec_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='webprintsubmission',
            name='fec_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
