# Generated by Django 3.2.12 on 2022-09-12 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("web_services", "0009_add_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dotfec",
            name="report",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="uploadsubmission",
            name="dot_fec",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="webprintsubmission",
            name="dot_fec",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dotfec",
            name="id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="dotfec",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.RenameField(
            model_name="uploadsubmission",
            old_name="dot_fec",
            new_name="dot_fec_old",
        ),
        migrations.RenameField(
            model_name="webprintsubmission",
            old_name="dot_fec",
            new_name="dot_fec_old",
        ),
    ]
