# Generated by Django 3.2.12 on 2022-09-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def update_uuid(apps, schema_editor):
        DotFEC = apps.get_model("web_services", "DotFEC")
        UploadSubmission = apps.get_model("web_services", "UploadSubmission")
        WebPrintSubmission = apps.get_model("web_services", "WebPrintSubmission")
        dot_fec_uuid = DotFEC.objects.filter(
            id=models.OuterRef("dot_fec_old")
        ).values_list("uuid")[:1]
        UploadSubmission.objects.update(dot_fec=models.Subquery(dot_fec_uuid))
        WebPrintSubmission.objects.update(dot_fec=models.Subquery(dot_fec_uuid))

    dependencies = [
        ("web_services", "0011_auto_20220912_1728"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsubmission",
            name="dot_fec",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_services.dotfec",
            ),
        ),
        migrations.AddField(
            model_name="webprintsubmission",
            name="dot_fec",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_services.dotfec",
            ),
        ),
        migrations.RunPython(update_uuid),
    ]
