# Generated by Django 3.2.12 on 2022-09-12 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("web_services", "0011_replace_fk"),
        ("f3x_summaries", "0019_f3xsummary_submission_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadsubmission",
            name="id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="uploadsubmission",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="webprintsubmission",
            name="id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="webprintsubmission",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
