# Generated by Django 3.2.12 on 2022-09-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_services", "0012_auto_20220912_1731"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dotfec",
            name="id",
        ),
        migrations.RemoveField(
            model_name="uploadsubmission",
            name="dot_fec_old",
        ),
        migrations.RemoveField(
            model_name="webprintsubmission",
            name="dot_fec_old",
        ),
    ]
