# Generated by Django 3.2.12 on 2022-09-12 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("web_services", "0012_use_uuid"),
        ("f3x_summaries", "0020_f3xsummary_submission_keys"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadsubmission",
            name="id",
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name="webprintsubmission",
            name="id",
            field=models.IntegerField(),
        ),
    ]
