# Generated by Django 3.2.12 on 2022-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f3x_summaries", "0025_auto_20220915_1309"),
        ("web_services", "0014_auto_20220915_1309"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dotfec",
            name="report",
        ),
        migrations.AddField(
            model_name="dotfec",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.CASCADE,
                to="f3x_summaries.F3XSummary",
            ),
        ),
    ]
