# Generated by Django 3.2.12 on 2022-09-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def clean_dotfec(apps, schema_editor):
        DotFEC = apps.get_model("web_services", "DotFEC")
        DotFEC.objects.all().delete()

    dependencies = [
        ("web_services", "0015_alter_dotfec_report_step_1"),
    ]

    operations = [
        migrations.RunPython(clean_dotfec),
        migrations.AlterField(
            model_name="dotfec",
            name="report",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, to="f3x_summaries.F3XSummary"
            ),
        ),
    ]
