# Generated by Django 4.1.3 on 2023-09-18 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '__first__'),
        ('web_services', '0017_alter_dotfec_report_step_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotfec',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.f3xreport'),
        ),
    ]
