# Generated by Django 4.1.3 on 2023-10-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_copy_to_unified_table"),
        ("web_services", "0017_alter_dotfec_report_step_3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dotfec",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.report",
            ),
        ),
    ]
