# Generated by Django 4.1.3 on 2023-10-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_form_type_report__form_type'),
        ('web_services', '0018_alter_dotfec_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotfec',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
    ]
