# Generated by Django 3.2.11 on 2022-02-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0002_auto_20220210_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='schatransaction',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
