# Generated by Django 3.2.11 on 2022-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0003_schatransaction_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schatransaction',
            name='back_reference_sched_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='back_reference_tran_id_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='conduit_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='conduit_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='conduit_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='conduit_street1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='conduit_street2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='conduit_zip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contribution_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contribution_purpose_descrip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_employer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_middle_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_organization_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_prefix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_street_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_street_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_suffix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_zip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='donor_candidate_district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='donor_candidate_fec_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='donor_candidate_first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='donor_candidate_last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='donor_candidate_middle_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='donor_candidate_office',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='donor_candidate_prefix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='donor_candidate_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='donor_candidate_suffix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='donor_committee_fec_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='donor_committee_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='election_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='election_other_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='entity_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='filer_committee_id_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='form_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='memo_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='memo_text_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='reference_to_si_or_sl_system_code_that_identifies_the_account',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='transaction_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='transaction_type_identifier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
