# Generated by Django 3.2.12 on 2022-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0004_auto_20220303_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_first_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_last_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contributor_organization_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='entity_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='filer_committee_id_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='form_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='transaction_id',
            field=models.TextField(null=True),
        ),
    ]
