# Generated by Django 3.2.12 on 2022-06-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scha_transactions", "0007_alter_schatransaction_committee_account"),
    ]

    operations = [
        migrations.AddField(
            model_name='schatransaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scha_transactions.schatransaction'),
        ),
    ]
