# Generated by Django 3.2.12 on 2022-05-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scha_transactions", "0007_alter_schatransaction_committee_account"),
    ]

    operations = [
        migrations.AddField(
            model_name='schatransaction',
            name='f3x_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='f3x_summaries.f3xsummary'),
        ),
    ]
