# Generated by Django 3.2.12 on 2022-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0007_alter_schatransaction_committee_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schatransaction',
            name='memo_code',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
