# Generated by Django 3.2.12 on 2022-06-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0008_alter_schatransaction_memo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schatransaction',
            name='contribution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
