# Generated by Django 3.2.12 on 2022-06-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0008_alter_schatransaction_memo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='schatransaction',
            name='transaction_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scha_transactions.schatransaction'),
        ),
    ]
