# Generated by Django 3.2.12 on 2022-06-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0009_alter_schatransaction_contribution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schatransaction',
            name='parent_transaction_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scha_transactions.schatransaction'),
        ),
    ]
