# Generated by Django 3.2.12 on 2022-07-01 19:19

from django.db import migrations, models
import django.db.models.deletion


def add_new_report_id(apps, schema_editor):
    SchATransaction = apps.get_model("scha_transactions", "SchATransaction") # noqa
    CommitteeAccount = apps.get_model("committee_accounts","CommitteeAccount") # noqa
    F3XSummary = apps.get_model("f3x_summaries","F3XSummary") # noqa

    for committee in CommitteeAccount.objects.all():
        c_id = committee.committee_id

        reports = F3XSummary.objects.filter(filer_committee_id_number=c_id)
        if len(reports) == 0:
            continue
        report = reports[0]

        for transaction in SchATransaction.objects.filter(filer_committee_id_number=c_id):
            transaction.report_id = report
            transaction.save()

def remove_report_id(apps, schema_editor):
    SchATransaction = apps.get_model("scha_transactions", "SchATransaction") # noqa
    for transaction in SchATransaction.objects.all():
        transaction.report_id = None
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('f3x_summaries', '0011_auto_20220609_1730'),
        ('scha_transactions', '0010_schatransaction_parent_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schatransaction',
            name='report_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='f3x_summaries.f3xsummary'),
        ),
        migrations.RunPython(add_new_report_id, remove_report_id),
    ]

