# Generated by Django 3.2.12 on 2022-07-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0011_schatransaction_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schatransaction',
            name='contribution_aggregate',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=11,
                null=True),
        ),
        migrations.AlterField(
            model_name='schatransaction',
            name='contribution_amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=11,
                null=True),
        ),
    ]
