# Generated by Django 3.2.12 on 2022-07-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scha_transactions", "0012_auto_20220713_1219"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schatransaction",
            old_name="parent_transaction_id",
            new_name="parent_transaction",
        ),
        migrations.RenameField(
            model_name="schatransaction",
            old_name="report_id",
            new_name="report",
        ),
    ]
