# Generated by Django 3.2.12 on 2022-08-03 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0013_auto_20220725_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='schatransaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
