# Generated by Django 3.2.12 on 2022-08-04 18:49

from django.db import migrations, models
import uuid


def check_for_uid_conflicts(apps, uid):
    SchATransaction = apps.get_model("scha_transactions", "SchATransaction")  # noqa
    for transaction in SchATransaction.objects.all():
        if transaction.transaction_id == uid:
            return True
    return False   

def generate_uids(apps, schema_editor):
    SchATransaction = apps.get_model("scha_transactions", "SchATransaction")  # noqa
    for transaction in SchATransaction.objects.all():
        u = uuid.uuid4()
        unique_id = str(u.hex)[-20:]

        attempts = 0
        while check_for_uid_conflicts(apps, unique_id):
            unique_id = str(u.hex)[-20:]
            attempts+=1
            if (attempts > 5):
                print("Unique ID generation failed: Over 5 conflicts in a row")
                return

        transaction.transaction_id = unique_id
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0013_auto_20220725_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schatransaction',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(code=generate_uids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='schatransaction',
            name='transaction_id',
            field=models.TextField(editable=False, max_length=20),
        ),
    ]
