# Generated by Django 3.2.12 on 2022-08-05 14:17

from django.db import migrations, models


def update_back_reference_ids(apps, schema_editor):
    SchATransaction = apps.get_model("scha_transactions", "SchATransaction")  # noqa
    for transaction in SchATransaction.objects.all():
        if transaction.parent_transaction:
            p_id = transaction.parent_transaction.transaction_id
            transaction.back_reference_tran_id_number = p_id
            transaction.save()


def remove_back_reference_ids(apps, schema_editor):
    SchATransaction = apps.get_model("scha_transactions", "SchATransaction")  # noqa
    for transaction in SchATransaction.objects.all():
        transaction.back_reference_tran_id_number = ""
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0014_schatransaction_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schatransaction',
            name='back_reference_tran_id_number',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(
            code=update_back_reference_ids,
            reverse_code=remove_back_reference_ids
        )
    ]
