# Generated by Django 3.2.12 on 2022-08-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scha_transactions",
            "0015_alter_schatransaction_back_reference_tran_id_number",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="schatransaction",
            name="scha_trans_transaction_id",
        ),
        migrations.AddIndex(
            model_name="schatransaction",
            index=models.Index(
                fields=["transaction_id"], name="scha_transa_transac_2cc8fa_idx"
            ),
        ),
    ]
