# Generated by Django 3.2.12 on 2022-08-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0016_auto_20220810_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name="schatransaction",
            name="contributor_last_name",
            field=models.BooleanField(blank=False, null=False),
        ),
    ]
