# Generated by Django 3.2.12 on 2022-09-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scha_transactions", "0017_schatransaction_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schatransaction",
            name="report",
            field=models.IntegerField(null=True),
        ),
    ]
