# Generated by Django 3.2.12 on 2022-10-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scha_transactions", "0025_update_transaction_identifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schatransaction",
            name="transaction_id",
            field=models.TextField(max_length=20, null=True),
        ),
    ]
