# Generated by Django 3.2.12 on 2022-10-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scha_transactions", "0027_scha_transaction_aggregation_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schatransaction", name="contribution_aggregate",
        ),
    ]
