# Generated by Django 3.2.12 on 2022-10-07 17:26

from django.db import migrations
from django.db.models import Value, Case, When, F, TextField


# Machine-generated dict right here.  Not sure it'd be worth it to break it up
non_contribution = "NON_CONTRIBUTION_ACCOUNT"
design_tbd = "DESIGN_TBD"
tid_to_aggregation_groups = {
    "PARTNERSHIP_JF_TRANSFER_MEMO": design_tbd,
    "PARTNERSHIP_INDIVIDUAL_JF_TRANSFER_MEMO": " DESIGN_TBD",
    "OFFSET_TO_OPERATING_EXPENDITURES": "LINE_15",
    "REFUND_TO_REGISTERED_COMMITTEE": "LINE_16",
    "REFUND_TO_UNREGISTERED_COMMITTEE": "LINE_16",
    "PARTNERSHIP_CONVENTION_JF_TRANSFER_MEMO": design_tbd,
    "PARTNERSHIP_INDIVIDUAL_CONVENTION_JF_TRANSFER_MEMO": design_tbd,
    "PARTNERSHIP_HEADQUARTERS_JF_TRANSFER_MEMO": design_tbd,
    "PARTNERSHIP_INDIVIDUAL_HEADQUARTERS_JF_TRANSFER_MEMO": design_tbd,
    "PARTNERSHIP_RECOUNT_JF_TRANSFER_MEMO": design_tbd,
    "PARTNERSHIP_INDIVIDUAL_RECOUNT_JF_TRANSFER_MEMO": design_tbd,
    "INDIVIDUAL_RECEIPT_NON_CONTRIBUTION_ACCOUNT": non_contribution,
    "OTHER_COMMITTEE_NON_CONTRIBUTION_ACCOUNT": non_contribution,
    "BUSINESS_LABOR_NON_CONTRIBUTION_ACCOUNT": non_contribution,
    "OTHER_RECEIPT": "OTHER_RECIEPTS",
}


def populate_aggregation_group_fields(apps, _):
    sch_a_transaction = apps.get_model("scha_transactions", "SchATransaction")  # noqa

    sch_a_transaction.objects.update(
        aggregation_group=Case(
            When(
                aggregation_group="NON-CONTRIBUTION_ACCOUNT",
                then=Value("NON_CONTRIBUTION_ACCOUNT", TextField()),
            ),
            When(
                aggregation_group=" DESIGN TBD", then=Value("DESIGN_TBD", TextField())
            ),
            When(
                aggregation_group="Other Receipts",
                then=Value("OTHER_RECIEPTS", TextField()),
            ),
            When(aggregation_group="Line 15", then=Value("LINE_15", TextField())),
            When(aggregation_group="Line 16", then=Value("LINE_16", TextField())),
            default=F("aggregation_group"),
        )
    )


def noop(_apps, _):
    # Empty function to pass as a reverse method to RunPython
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scha_transactions", "0028_remove_schatransaction_contribution_aggregate"),
    ]

    operations = [
        migrations.RunPython(populate_aggregation_group_fields, noop),
    ]
