# Generated by Django 3.2.12 on 2022-10-07 17:26

from django.db import migrations
from django.db.models import Value, Case, When, F, TextField


def populate_aggregation_group_fields(apps, _):
    sch_a_transaction = apps.get_model("scha_transactions", "SchATransaction")  # noqa

    sch_a_transaction.objects.update(
        aggregation_group=Case(
            When(
                aggregation_group="NON-CONTRIBUTION_ACCOUNT",
                then=Value("NON_CONTRIBUTION_ACCOUNT", TextField()),
            ),
            When(
                aggregation_group=" DESIGN TBD", then=Value("DESIGN_TBD", TextField())
            ),
            When(
                aggregation_group="Other Receipts",
                then=Value("OTHER_RECIEPTS", TextField()),
            ),
            When(aggregation_group="Line 15", then=Value("LINE_15", TextField())),
            When(aggregation_group="Line 16", then=Value("LINE_16", TextField())),
            default=F("aggregation_group"),
        )
    )


def noop(_apps, _):
    # Empty function to pass as a reverse method to RunPython
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scha_transactions", "0029_remove_schatransaction_contribution_aggregate"),
    ]

    operations = [
        migrations.RunPython(populate_aggregation_group_fields, noop),
    ]
