# Generated by Django 3.2.12 on 2022-10-07 17:26

from django.db import migrations
from django.db.models import Value, Case, When, F, TextField


def populate_aggregation_group_fields(apps, _):
    sch_a_transaction = apps.get_model("scha_transactions", "SchATransaction")  # noqa

    sch_a_transaction.objects.update(
        aggregation_group=Case(
            When(
                aggregation_group="OTHER_RECIEPTS",
                then=Value("OTHER_RECEIPTS", TextField()),
            ),
            default=F("aggregation_group"),
        )
    )


def noop(_apps, _):
    # Empty function to pass as a reverse method to RunPython
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scha_transactions", "0030_alter_schatransaction_transaction_id"),
    ]

    operations = [
        migrations.RunPython(populate_aggregation_group_fields, noop),
    ]
