# Generated by Django 3.2.12 on 2022-10-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo_text', '0007_auto_20220915_1309'),
        ('scha_transactions', '0031_update_other_receipts_aggregation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='schatransaction',
            name='memo_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memo_text.memotext'),
        ),
    ]
