# Generated by Django 3.2.12 on 2022-10-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scha_transactions', '0033_memo_description_to_memo_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schatransaction',
            name='memo_text_description',
        )
    ]
