# Generated by Django 5.2.11 on 2026-03-06 22:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("committee_accounts", "0001_initial"),
        ("committee_accounts", "0002_membership"),
        (
            "committee_accounts",
            "0003_membership_pending_email_alter_membership_id_and_more",
        ),
        ("committee_accounts", "0004_remove_duplicate_memberships"),
        ("committee_accounts", "0005_remove_pending_emails"),
        ("committee_accounts", "0006_alter_membership_committee_account_and_more"),
        ("committee_accounts", "0007_alter_committeeaccount_members"),
    ]

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeAccount",
            fields=[
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "committee_id",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^C[0-9]{8}$", "invalid committee id format"
                            )
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "committee_accounts",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("COMMITTEE_ADMINISTRATOR", "Committee Administrator"),
                            ("MANAGER", "Manager"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "pending_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "committee_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="committee_accounts.committeeaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="committeeaccount",
            name="members",
            field=models.ManyToManyField(
                through="committee_accounts.Membership",
                through_fields=("committee_account", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
