# Generated by Django 5.2.11 on 2026-03-06 22:00

import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models
from django_migration_linter import IgnoreMigration


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# fecfiler.committee_accounts.migrations.0002_membership
# fecfiler.committee_accounts.migrations.0003_membership_pending_email_alter_membership_id_and_more
# fecfiler.committee_accounts.migrations.0004_remove_duplicate_memberships
# fecfiler.committee_accounts.migrations.0005_remove_pending_emails


def create_memberships(apps, schema_editor):
    CommitteeAccount = apps.get_model("committee_accounts", "CommitteeAccount")
    User = apps.get_model("user", "User")
    Membership = apps.get_model("committee_accounts", "Membership")
    db_alias = schema_editor.connection.alias
    users = User.objects.using(db_alias).all()
    for user in users:
        committee = (
            CommitteeAccount.objects.using(db_alias)
            .filter(committee_id=user.cmtee_id)
            .first()
        )
        if committee:
            Membership.objects.create(
                user=user,
                committee_account=committee,
                role="COMMITTEE_ADMINISTRATOR",
            )


def delete_pending_memberships(apps, schema_editor):
    Membership = apps.get_model("committee_accounts", "Membership")
    Membership.objects.filter(user=None).delete()


def generate_new_uuid(apps, schema_editor):
    Membership = apps.get_model("committee_accounts", "Membership")
    for membership in Membership.objects.all():
        membership.uuid = uuid.uuid4()
        membership.save()


def delete_memberships_with_overlapping_emails(apps, schema_editor):
    Membership = apps.get_model("committee_accounts", "Membership")
    Committee = apps.get_model("committee_accounts", "CommitteeAccount")

    for committee in Committee.objects.all():
        committee_memberships = Membership.objects.filter(committee_account=committee)
        unique_pending_emails = set()
        emails_to_prune = set()

        for membership in committee_memberships:
            pending_email = str(membership.pending_email).lower()
            if pending_email not in unique_pending_emails:
                unique_pending_emails.add(pending_email)
            else:
                emails_to_prune.add(pending_email)

        for email in list(emails_to_prune):
            overlapping_memberships = list(
                committee_memberships.filter(pending_email__iexact=email).order_by("user")
            )
            for membership_to_delete in overlapping_memberships[1:]:
                membership_to_delete.delete()


def remove_pending_emails(apps, schema_editor):
    Membership = apps.get_model("committee_accounts", "Membership")
    Membership.objects.filter(pending_email__isnull=False, user_id__isnull=False).update(
        pending_email=None
    )


class Migration(migrations.Migration):

    replaces = [
        ("committee_accounts", "0001_initial"),
        ("committee_accounts", "0002_membership"),
        (
            "committee_accounts",
            "0003_membership_pending_email_alter_membership_id_and_more",
        ),
        ("committee_accounts", "0004_remove_duplicate_memberships"),
        ("committee_accounts", "0005_remove_pending_emails"),
        ("committee_accounts", "0006_alter_membership_committee_account_and_more"),
        ("committee_accounts", "0007_alter_committeeaccount_members"),
    ]

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        IgnoreMigration(),
        migrations.CreateModel(
            name="CommitteeAccount",
            fields=[
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "committee_id",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^C[0-9]{8}$", "invalid committee id format"
                            )
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "committee_accounts",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("COMMITTEE_ADMINISTRATOR", "Committee Administrator"),
                            ("REVIEWER", "Reviewer"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "committee_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="committee_accounts.committeeaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="committeeaccount",
            name="members",
            field=models.ManyToManyField(
                through="committee_accounts.Membership", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(
            code=create_memberships,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="membership",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False),
        ),
        migrations.RunPython(
            code=generate_new_uuid,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="membership",
            name="id",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="membership",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="membership",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(
            code=django.db.migrations.operations.special.RunPython.noop,
            reverse_code=delete_pending_memberships,
        ),
        migrations.RunPython(
            code=delete_memberships_with_overlapping_emails,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=remove_pending_emails,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="membership",
            name="committee_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="committee_accounts.committeeaccount",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("COMMITTEE_ADMINISTRATOR", "Committee Administrator"),
                    ("MANAGER", "Manager"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="committeeaccount",
            name="members",
            field=models.ManyToManyField(
                through="committee_accounts.Membership",
                through_fields=("committee_account", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
