# Generated by Django 3.2.12 on 2022-06-23 14:50

from django.db import migrations

def forwards_func(apps, schema_editor):
    call_command(
        "loaddata",
        "fecfiler/committee_accounts/fixtures/test-extra-users.json",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('committee_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]

