# Generated by Django 3.2.12 on 2022-09-09 16:41

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    CommitteeAccount = apps.get_model("committee_accounts", "CommitteeAccount")  # noqa
    for committee_account in CommitteeAccount.objects.all():
        committee_account.uuid = uuid.uuid4()
        committee_account.save()


class Migration(migrations.Migration):

    dependencies = [
        ("committee_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="committeeaccount",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(create_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="committeeaccount",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
