# Generated by Django 3.2.12 on 2022-09-09 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("committee_accounts", "0002_committeeaccount_uuid"),
        ("contacts", "0008_committee_fk_to_int"),
        ("f3x_summaries", "0023_committee_fk_to_int"),
        ("memo_text", "0005_committee_fk_to_int"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeeaccount",
            name="id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="committeeaccount",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
