# Generated by Django 4.2.7 on 2024-02-16 20:43

from django.conf import settings
from django.db import migrations


def delete_memberships_with_overlapping_emails(apps, schema_editor):
    Membership = apps.get_model("committee_accounts", "Membership")  # noqa
    Committee = apps.get_model("committee_accounts", "CommitteeAccount")  # noqa

    for committee in Committee.objects.all():
        committee_memberships = Membership.objects.filter(committee_account=committee)

        unique_pending_emails = set()
        emails_to_prune = set()
        for membership in committee_memberships:
            pending_email = str(membership.pending_email).lower()
            if pending_email not in unique_pending_emails:
                unique_pending_emails.add(pending_email)
            else:
                emails_to_prune.add(pending_email)

        for email in list(emails_to_prune):
            # ordering by user places any memberships with a user first
            overlapping_memberships = list(
                committee_memberships.filter(pending_email__iexact=email).order_by('user')
            )
            for membership_to_delete in overlapping_memberships[1:]:
                membership_to_delete.delete()


class Migration(migrations.Migration):

    dependencies = [(
        'committee_accounts',
        '0003_membership_pending_email_alter_membership_id_and_more'
    )]

    operations = [
        migrations.RunPython(
            delete_memberships_with_overlapping_emails,
            migrations.RunPython.noop,
        ),
    ]
