# Generated by Django 3.2.12 on 2022-09-09 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("committee_accounts", "0003_uuid_pk"),
        ("contacts", "0009_committee_uuid_fk"),
        ("f3x_summaries", "0024_committee_uuid_fk"),
        ("memo_text", "0006_committee_uuid_fk"),
        ("scha_transactions", "0022_committee_uuid_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="committeeaccount",
            name="id",
        ),
    ]
