# Generated by Django 5.1.4 on 2025-02-05 18:11

from django.db import migrations


def remove_pending_emails(apps, schema_editor):
    # remove pending emails from memberships that have been redeemed
    Membership = apps.get_model("committee_accounts", "Membership")  # noqa
    Membership.objects.filter(pending_email__isnull=False, user_id__isnull=False).update(
        pending_email=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("committee_accounts", "0004_remove_duplicate_memberships"),
    ]

    operations = [
        migrations.RunPython(remove_pending_emails),
    ]
