# Generated by Django 3.2.12 on 2022-09-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee_accounts', '0004_remove_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeeaccount',
            old_name='uuid',
            new_name='id',
        ),
    ]
