# Generated by Django 5.1.5 on 2025-02-13 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committee_accounts", "0005_remove_pending_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="committee_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="committee_accounts.committeeaccount",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("COMMITTEE_ADMINISTRATOR", "Committee Administrator"),
                    ("REVIEWER", "Reviewer"),
                    ("MANAGER", "Manager"),
                ],
                max_length=25,
            ),
        ),
    ]
