# Generated by Django 5.2.12 on 2026-03-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_accounts', '0001_squashed_0007_alter_committeeaccount_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeaccount',
            name='disabled',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
