# Generated by Django 5.2.14 on 2026-06-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_accounts', '0008_committeeaccount_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeaccount',
            name='filing_frequency',
            field=models.TextField(blank=True, max_length=1, null=True),
        ),
    ]
