# Generated by Django 5.2.14 on 2026-07-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_accounts', '0009_committeeaccount_filing_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeaccount',
            name='candidate_office',
            field=models.CharField(
                blank=True,
                choices=[('H', 'House'), ('S', 'Senate'), ('P', 'Presidential')],
                max_length=1,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='committeeaccount',
            name='candidate_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
