# Generated by Django 5.2.14 on 2026-07-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_accounts', '0010_committeeaccount_candidate_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeaccount',
            name='candidate_district',
            field=models.TextField(blank=True, null=True),
        ),
    ]
