# Generated by Django 4.2.7 on 2024-01-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("reports", "0001_initial"),
        ("web_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="upload_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_services.uploadsubmission",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="webprint_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_services.webprintsubmission",
            ),
        ),
        migrations.AddField(
            model_name="form1m",
            name="contact_affiliated",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_affiliated_transaction_set",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="form1m",
            name="contact_candidate_I",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_candidate_I_transaction_set",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="form1m",
            name="contact_candidate_II",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_candidate_II_transaction_set",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="form1m",
            name="contact_candidate_III",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_candidate_III_transaction_set",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="form1m",
            name="contact_candidate_IV",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_candidate_IV_transaction_set",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="form1m",
            name="contact_candidate_V",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_candidate_V_transaction_set",
                to="contacts.contact",
            ),
        ),
    ]
