# Generated by Django 4.1.3 on 2023-10-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_f24'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportf24',
            name='date_signed',
        ),
        migrations.RemoveField(
            model_name='reportf24',
            name='treasurer_first_name',
        ),
        migrations.RemoveField(
            model_name='reportf24',
            name='treasurer_last_name',
        ),
        migrations.RemoveField(
            model_name='reportf24',
            name='treasurer_middle_name',
        ),
        migrations.RemoveField(
            model_name='reportf24',
            name='treasurer_prefix',
        ),
        migrations.RemoveField(
            model_name='reportf24',
            name='treasurer_suffix',
        ),
        migrations.RemoveField(
            model_name='reportf3x',
            name='calculation_status',
        ),
        migrations.RemoveField(
            model_name='reportf3x',
            name='committee_name',
        ),
        migrations.RemoveField(
            model_name='reportf3x',
            name='coverage_from_date',
        ),
        migrations.RemoveField(
            model_name='reportf3x',
            name='coverage_through_date',
        ),
        migrations.RemoveField(
            model_name='reportf3x',
            name='date_signed',
        ),
        migrations.RemoveField(
            model_name='reportf3x',
            name='report_code',
        ),
        migrations.RemoveField(
            model_name='reportf3x',
            name='treasurer_first_name',
        ),
        migrations.RemoveField(
            model_name='reportf3x',
            name='treasurer_last_name',
        ),
        migrations.RemoveField(
            model_name='reportf3x',
            name='treasurer_middle_name',
        ),
        migrations.RemoveField(
            model_name='reportf3x',
            name='treasurer_prefix',
        ),
        migrations.RemoveField(
            model_name='reportf3x',
            name='treasurer_suffix',
        ),
        migrations.AddField(
            model_name='report',
            name='calculation_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='coverage_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='coverage_through_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='date_signed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='treasurer_first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='treasurer_last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='treasurer_middle_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='treasurer_prefix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='treasurer_suffix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='report',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reportf24',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reportf3x',
            table=None,
        ),
    ]
