# Generated by Django 4.1.3 on 2023-10-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_move_fields_between_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="report_version",
            field=models.TextField(blank=True, null=True),
        ),
    ]
