# Generated by Django 4.2.7 on 2024-03-08 16:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [
        ('reports', '0005_remove_form1m_iii_candidate_district_and_more'),
        ('reports', '0006_reporttransaction'),
    ]

    dependencies = [
        (
            "committee_accounts",
            "0001_squashed_0007_alter_committeeaccount_members",
        ),
        ('transactions', '0001_initial'),
        ('reports', '0004_form1m_date_committee_met_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTransaction',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False,
                    unique=True)
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='reports.report')
                ),
                ('transaction', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='transactions.transaction')
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
