# Generated by Django 4.2.7 on 2024-01-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_form1m_date_committee_met_requirements_and_more'),
    ]

    operations = []
