# Generated by Django 4.1.3 on 2023-11-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_form99_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='calculation_token',
            field=models.UUIDField(blank=True, null=True, default=None),
        ),
    ]
