# Generated by Django 5.2.11 on 2026-03-07 03:24

import django.db.models.deletion
import uuid
from django.db import migrations, models, connection


def _create_can_delete_trigger(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
        CREATE OR REPLACE FUNCTION check_can_delete()
        RETURNS TRIGGER AS $$
        BEGIN
            PERFORM update_report_can_delete(NEW);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE OR REPLACE FUNCTION check_can_delete_previous()
        RETURNS TRIGGER AS $$
        DECLARE
            associated_report RECORD;
        BEGIN
            FOR associated_report IN (
                SELECT * FROM reports_report
                WHERE committee_account_id = OLD.committee_account_id
                AND can_delete = false
            )
            LOOP
                PERFORM update_report_can_delete(associated_report);
            END LOOP;

            RETURN OLD;
        END;
        $$ LANGUAGE plpgsql;


        CREATE OR REPLACE FUNCTION check_can_delete_transaction_update()
        RETURNS TRIGGER AS $$
        DECLARE
            associated_report RECORD;
        BEGIN
            SELECT * INTO associated_report FROM reports_report WHERE id IN (
                    SELECT report_id FROM reports_reporttransaction
                    WHERE transaction_id = NEW.id LIMIT 1
                );
                PERFORM update_report_can_delete(associated_report);

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE OR REPLACE FUNCTION check_can_delete_transaction_insert()
        RETURNS TRIGGER AS $$
        DECLARE
             associated_report RECORD;
        BEGIN
            FOR associated_report IN (
                SELECT r1.*
                FROM reports_report r1
                JOIN reports_report r2
                    ON r1.committee_account_id = r2.committee_account_id
                    AND EXTRACT(YEAR FROM r1.coverage_from_date) = (
                        EXTRACT(YEAR FROM r2.coverage_from_date))
                WHERE r1.can_delete = true
                AND r2.id = NEW.report_id
            )
        LOOP
            PERFORM update_report_can_delete(associated_report);
        END LOOP;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER check_can_delete_report
        AFTER INSERT OR UPDATE ON reports_report
        FOR EACH ROW
        WHEN (pg_trigger_depth() = 0) -- Prevent infinite trigger loop
        EXECUTE FUNCTION check_can_delete();

        CREATE TRIGGER check_can_delete_previous
        AFTER DELETE ON reports_report
        FOR EACH ROW
        WHEN (pg_trigger_depth() = 0) -- Prevent infinite trigger loop
        EXECUTE FUNCTION check_can_delete_previous();

        CREATE TRIGGER check_can_delete_transaction_insert
        AFTER INSERT ON reports_reporttransaction
        FOR EACH ROW
        WHEN (pg_trigger_depth() = 0) -- Prevent infinite trigger loop
        EXECUTE FUNCTION check_can_delete_transaction_insert();
        """
        )


def _reverse_can_delete_trigger(apps, schema_editor):
    report_model = apps.get_model("reports", "Report")
    transaction_model = apps.get_model("transactions", "Transaction")

    triggers = [
        "check_can_delete_report",
        "check_can_delete_previous",
        "check_can_delete_transaction_update",
        "check_can_delete_transaction_insert",
    ]

    with schema_editor.atomic():
        for trigger in triggers:
            schema_editor.execute(
                "DROP TRIGGER IF EXISTS %s ON %s",
                (trigger, report_model._meta.db_table),
            )
            schema_editor.execute(
                "DROP TRIGGER IF EXISTS %s ON %s",
                (trigger, transaction_model._meta.db_table),
            )


def _create_can_unamend_trigger(apps, schema_editor):
    schema_editor.execute(
        """
    CREATE OR REPLACE FUNCTION update_can_unamend()
    RETURNS TRIGGER AS $$
    BEGIN
        UPDATE reports_report
        SET can_unamend = FALSE
        WHERE id IN (
            SELECT report_id
            FROM reports_reporttransaction
            WHERE transaction_id = NEW.id
        );
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER transaction_updated
    AFTER UPDATE ON transactions_transaction
    FOR EACH ROW
    WHEN (pg_trigger_depth() = 0) -- Prevent infinite trigger loop
    EXECUTE FUNCTION update_can_unamend();

    CREATE OR REPLACE FUNCTION update_can_unamend_new_transaction()
    RETURNS TRIGGER AS $$
    BEGIN
        UPDATE reports_report
        SET can_unamend = FALSE
        WHERE id IN (
            SELECT report_id
            FROM reports_reporttransaction
            WHERE id = NEW.id
        );
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER transaction_created
    AFTER INSERT ON reports_reporttransaction
    FOR EACH ROW
    WHEN (pg_trigger_depth() = 0) -- Prevent infinite trigger loop
    EXECUTE FUNCTION update_can_unamend_new_transaction();
    """
    )


class Migration(migrations.Migration):

    replaces = [
        ("reports", "0007_remove_report_deleted"),
        ("reports", "0008_remove_form1m_city_remove_form1m_committee_name_and_more"),
        ("reports", "0009_report_can_delete"),
        ("reports", "0010_report_can_unammend"),
        ("reports", "0011_remove_form3x_cash_on_hand_date"),
        ("reports", "0012_alter_form99_text_code"),
        ("reports", "0013_form3_report_form_3"),
        ("reports", "0014_form99_swap_text_code"),
        ("reports", "0015_form3x_filing_frequency_form3x_report_type_category"),
        ("reports", "0016_determine_frequency_and_category"),
        ("reports", "0017_form99_filing_frequency_form99_pdf_attachment"),
        ("reports", "00018_form24_name"),
        ("reports", "00019_form24_name_fix"),
    ]

    dependencies = [
        ("reports", "0005_remove_form1m_squashed_0006_reporttransaction"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION update_report_can_delete(report RECORD)
                RETURNS VOID AS $$
                DECLARE
                    r_can_delete boolean;
                BEGIN
                     r_can_delete = report.upload_submission_id IS NULL
                        AND (report.report_version IS NULL OR report.report_version = '0')
                        AND (
                            report.form_3x_id IS NULL OR
                            (
                                report.form_24_id IS NULL
                                AND NOT EXISTS(
                                    SELECT DISTINCT rrt1.id
                                    FROM "reports_reporttransaction" rrt1
                                        JOIN "transactions_transaction" tt ON (
                                        rrt1."transaction_id" = tt."id"
                                        OR tt."reatt_redes_id" = rrt1."transaction_id"
                                        OR tt."parent_transaction_id" =
                                            rrt1."transaction_id"
                                        OR tt."debt_id" = rrt1."transaction_id"
                                        OR tt."loan_id" = rrt1."transaction_id"
                                    )
                                        INNER JOIN "reports_reporttransaction" rrt2 ON (
                                        rrt2."transaction_id" = tt."id"
                                        AND rrt2."report_id" <> report.id
                                    )
                                    WHERE rrt1."report_id" = report.id
                                )
                            )
                        );
                    UPDATE reports_report SET can_delete = r_can_delete
                    WHERE id = report.id
                    AND can_delete <> r_can_delete;
                END;
                $$ LANGUAGE plpgsql;
            """
        ),
        migrations.RunPython(
            code=_create_can_delete_trigger,
            reverse_code=_reverse_can_delete_trigger,
        ),
        migrations.RunPython(
            code=_create_can_unamend_trigger,
        ),
        migrations.CreateModel(
            name="Form3",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "change_of_address",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("election_state", models.TextField(blank=True, null=True)),
                ("election_district", models.TextField(blank=True, null=True)),
                ("election_code", models.TextField(blank=True, null=True)),
                ("date_of_election", models.DateField(blank=True, null=True)),
                ("state_of_election", models.TextField(blank=True, null=True)),
                (
                    "L6a_total_contributions_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L6b_total_contribution_refunds_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L6c_net_contributions_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L7a_total_operating_expenditures_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L7b_total_offsets_to_operating_expenditures_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L7c_net_operating_expenditures_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L8_cash_on_hand_at_close_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L9_debts_owed_to_committee_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L10_debts_owed_by_committee_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11ai_individuals_itemized_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11aii_individuals_unitemized_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11aiii_total_individual_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11b_political_party_committees_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11c_other_political_committees_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11d_the_candidate_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11e_total_contributions_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L12_transfers_from_other_authorized_committees_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L13a_loans_made_or_guaranteed_by_the_candidate_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L13b_all_other_loans_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L13c_total_loans_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L14_offsets_to_operating_expenditures_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L15_other_receipts_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L16_total_receipts_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L17_operating_expenditures_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L18_transfers_to_other_authorized_committees_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L19a_loan_repayments_of_loans_made_or_"
                    "guaranteed_by_candidate_period",
                    models.DecimalField(
                        blank=True,
                        db_column="l19a_period",
                        decimal_places=2,
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "L19b_loan_repayments_of_all_other_loans_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L19c_total_loan_repayments_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L20a_refunds_to_individuals_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L20b_refunds_to_political_party_committees_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L20c_refunds_to_other_political_committees_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L20d_total_contribution_refunds_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L21_other_disbursements_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L22_total_disbursements_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L23_cash_on_hand_beginning_reporting_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L24_total_receipts_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L25_subtotals_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L26_total_disbursements_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L27_cash_on_hand_at_close_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L6a_total_contributions_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L6b_total_contribution_refunds_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L6c_net_contributions_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L7a_total_operating_expenditures_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L7b_total_offsets_to_operating_expenditures_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L7c_net_operating_expenditures_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11ai_individuals_itemized_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11aii_individuals_unitemized_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11aiii_total_individual_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11b_political_party_committees_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11c_other_political_committees_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11d_the_candidate_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L11e_total_contributions_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L12_transfers_from_other_authorized_committees_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L13a_loans_made_or_guaranteed_by_the_candidate_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L13b_all_other_loans_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L13c_total_loans_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L14_offsets_to_operating_expenditures_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L15_other_receipts_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L16_total_receipts_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L17_operating_expenditures_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L18_transfers_to_other_authorized_committees_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L19a_loan_repayments_of_loans_made_or_guaranteed_by_candidate_ytd",
                    models.DecimalField(
                        blank=True,
                        db_column="l19a_ytd",
                        decimal_places=2,
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "L19b_loan_repayments_of_all_other_loans_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L19c_total_loan_repayments_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L20a_refunds_to_individuals_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L20b_refunds_to_political_party_committees_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L20c_refunds_to_other_political_committees_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L20d_total_contribution_refunds_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L21_other_disbursements_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "L22_total_disbursements_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="report",
            name="form_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.form3",
            ),
        ),
        migrations.AddField(
            model_name="form3x",
            name="filing_frequency",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form3x",
            name="report_type_category",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form99",
            name="pdf_attachment",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form99",
            name="filing_frequency",
            field=models.TextField(blank=True, max_length=1, null=True),
        ),
    ]
