# Generated by Django 4.2.7 on 2023-12-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_update_l6a_coh_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form99',
            old_name='text',
            new_name='message_text',
        ),
    ]
