# Generated by Django 4.2.7 on 2024-04-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_report_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='form3x',
            name='committee_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
