# Generated by Django 4.2.10 on 2024-04-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_remove_form1m_city_remove_form1m_committee_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="city",
            field=models.TextField(blank=True, null=True),
        ),
    ]
