# Generated by Django 4.2.7 on 2023-12-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_rename_text_form99_text_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='form99',
            name='committee_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
