# Generated by Django 4.2.11 on 2024-07-02 17:21

from django.db import migrations, models
from django.db import connection


def populate_existing_rows(apps, schema_editor):
    report_model = apps.get_model("reports", "Report")
    for row in report_model.objects.all():
        row.can_delete = False
        row.save()


def create_trigger(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
        CREATE OR REPLACE FUNCTION check_can_delete() RETURNS TRIGGER AS $$
        DECLARE
            associated_report reports_report%ROWTYPE;
        BEGIN

            IF (TG_TABLE_NAME = 'transactions_transaction') THEN
                SELECT * INTO associated_report FROM reports_report WHERE id IN (
                    SELECT report_id FROM reports_reporttransaction
                    WHERE transaction_id = NEW.id LIMIT 1
                );
            ELSE
                associated_report := NEW;
            END IF;

            associated_report.can_delete = associated_report.upload_submission_id IS NULL
                AND (associated_report.report_version IS NULL
                OR associated_report.report_version = '0')
                AND (associated_report.form_3x_id IS NULL OR (
                    associated_report.form_24_id IS NULL
                    AND NOT EXISTS (
                        SELECT 1
                        FROM reports_reporttransaction AS rt1
                        JOIN transactions_transaction AS t1 ON rt1.transaction_id = t1.id
                        WHERE rt1.report_id = associated_report.id
                        AND EXISTS (
                            SELECT 1
                            FROM reports_reporttransaction AS rt2
                            WHERE rt2.report_id != associated_report.id
                            AND (
                                t1.id = rt2.transaction_id
                                OR t1.reatt_redes_id = rt2.transaction_id
                                OR t1.parent_transaction_id = rt2.transaction_id
                                OR t1.debt_id = rt2.transaction_id
                                OR t1.loan_id = rt2.transaction_id
                            )
                        )
                    )
                ));

            UPDATE reports_report SET can_delete = associated_report.can_delete
            WHERE id = associated_report.id;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER check_can_delete_report
        AFTER UPDATE ON reports_report
        FOR EACH ROW
        WHEN (pg_trigger_depth() = 0) -- Prevent infinite trigger loop
        EXECUTE FUNCTION check_can_delete();

        CREATE TRIGGER check_can_delete_transaction
        AFTER INSERT OR UPDATE ON transactions_transaction
        FOR EACH ROW
        WHEN (pg_trigger_depth() = 0) -- Prevent infinite trigger loop
        EXECUTE FUNCTION check_can_delete();
        """
        )


def reverse_code(apps, schema_editor):
    # Get models
    report_model = apps.get_model("reports", "Report")
    transaction_model = apps.get_model("transactions", "Transaction")

    # Drop triggers
    triggers = [
        "check_can_delete_report",
        "check_can_delete_transaction",
    ]

    with schema_editor.atomic():
        for trigger in triggers:
            schema_editor.execute(
                "DROP TRIGGER IF EXISTS %s ON %s", (trigger, report_model._meta.db_table)
            )
            schema_editor.execute(
                "DROP TRIGGER IF EXISTS %s ON %s",
                (trigger, transaction_model._meta.db_table),
            )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_remove_form1m_city_remove_form1m_committee_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="can_delete",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(create_trigger, reverse_code),
        migrations.RunPython(populate_existing_rows),
    ]
