# Generated by Django 5.2.13 on 2026-05-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_can_unamend_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='form3',
            name='report_type_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
