# Generated by Django 5.2.13 on 2026-05-27 16:44

from django.db import migrations, models


def copy_report_id_to_fec_report_id(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    Report.objects.exclude(report_id__isnull=True).update(
        fec_report_id=models.F("report_id")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_remove_can_unamend_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="fec_report_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="previous_upload_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                to="web_services.uploadsubmission",
            ),
        ),
        migrations.RunPython(copy_report_id_to_fec_report_id),
    ]
