# Generated by Django 4.2.7 on 2024-01-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_contact_id'),
        ('reports', '0009_form99_committee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1m',
            name='committee_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form1m',
            name='contact_affiliated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_affiliated_transaction_set', to='contacts.contact'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='form1m',
            name='contact_candidate_I',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_candidate_I_transaction_set', to='contacts.contact'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='form1m',
            name='contact_candidate_II',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_candidate_II_transaction_set', to='contacts.contact'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='form1m',
            name='contact_candidate_III',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_candidate_III_transaction_set', to='contacts.contact'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='form1m',
            name='contact_candidate_IV',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_candidate_IV_transaction_set', to='contacts.contact'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='form1m',
            name='contact_candidate_V',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_candidate_V_transaction_set', to='contacts.contact'),  # noqa: E501
        ),
    ]
