# Generated by Django 5.2.13 on 2026-05-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_rename_report_id_report_fec_report_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="form3",
            name="report_type_category",
            field=models.TextField(blank=True, null=True),
        ),
    ]
