# Generated by Django 5.2.14 on 2026-06-02 16:42

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):
    def copy_fec_report_id_to_report_id(apps, schema_editor):
        Report = apps.get_model("reports", "Report")
        Report.objects.exclude(fec_report_id__isnull=True).update(
            report_id=models.F("fec_report_id")
        )

    dependencies = [
        ("reports", "0010_form3_report_type_category"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=copy_fec_report_id_to_report_id,
        ),
        migrations.RemoveField(
            model_name="report",
            name="report_id",
        ),
    ]
