# Generated by Django 4.2.7 on 2024-01-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_form1m_committee_name_form1m_contact_affiliated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form1m',
            old_name='III_candidate_id_number',
            new_name='III_candidate_id',
        ),
        migrations.RenameField(
            model_name='form1m',
            old_name='II_candidate_id_number',
            new_name='II_candidate_id',
        ),
        migrations.RenameField(
            model_name='form1m',
            old_name='IV_candidate_id_number',
            new_name='IV_candidate_id',
        ),
        migrations.RenameField(
            model_name='form1m',
            old_name='I_candidate_id_number',
            new_name='I_candidate_id',
        ),
        migrations.RenameField(
            model_name='form1m',
            old_name='V_candidate_id_number',
            new_name='V_candidate_id',
        ),
    ]
