# Generated by Django 4.2.7 on 2024-01-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_form1m_committee_name_form1m_contact_affiliated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1m',
            name='date_committee_met_requirements',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form1m',
            name='date_of_51st_contributor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form1m',
            name='date_of_original_registration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
