# Generated by Django 5.0.8 on 2024-09-20 19:31

from django.db import migrations, models


def default_f3x_qualified_committee_to_none(apps, schema_editor):
    Report = apps.get_model("reports", "Report")  # noqa
    reports_to_update = Report.objects.filter(
        form_3x__isnull=False,
        form_3x__qualified_committee=False  # the old default value
    )
    for report in reports_to_update:
        report.form_3x.qualified_committee=True
        report.form_3x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_report_can_unammend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form3x',
            name='qualified_committee',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.RunPython(
            default_f3x_qualified_committee_to_none,
            migrations.RunPython.noop
        ),
    ]
