# Generated by Django 4.2.11 on 2024-10-23 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0010_report_can_unammend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form3x",
            name="cash_on_hand_date",
        ),
    ]
