# Generated by Django 5.2.14 on 2026-06-23 05:19

from django.db import migrations
from fecfiler.transactions.models import Transaction


def update_line_numbers(apps, schema_editor):
    print("\n=================\n" "Starting update of line numbers")
    transaction_count = Transaction.objects.count()
    print(f"Total transactions: {transaction_count}")
    unassigned_transactions = Transaction.objects.filter(reports__isnull=True)
    f3_transactions = Transaction.objects.filter(reports__form_3_id__isnull=False)
    print(
        "=================\n"
        f"Unassigned transactions: {unassigned_transactions.count()}"
    )
    for transaction in unassigned_transactions:
        transaction.set_and_save_form_type()
    print(f"Finished updating unassigned transactions")

    print(f"=================\n" f"Form 3 transactions: {f3_transactions.count()}")
    f3_transactions_updated = 0
    for transaction in unassigned_transactions.union(f3_transactions):
        transaction.set_and_save_form_type()
        if transaction._form_type:
            f3_transactions_updated += 1
        else:
            print(f"Transaction had no _form_type, ID: {transaction.id}")
    print(f"Form 3 transactions updated: {f3_transactions_updated}")


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0012_remove_can_delete_triggers"),
    ]

    operations = [
        migrations.RunPython(
            code=update_line_numbers,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
