# Generated by Django 5.2 on 2025-05-13 19:21

from django.db import migrations, models


def form_99_add_default_text_code(apps, schema_editor):
    Report = apps.get_model("reports", "Report")  # noqa
    reports_to_update = Report.objects.filter(
        models.Q(form_99__text_code__isnull=True)
        | models.Q(form_99__text_code="")
    )
    for report in reports_to_update:
        report.form_99.text_code = "MST"
        report.form_99.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_form99_swap_text_code'),
    ]

    operations = [
        migrations.RunPython(form_99_add_default_text_code, migrations.RunPython.noop),
        migrations.AddField(
            model_name='form99',
            name='filing_frequency',
            field=models.TextField(blank=True, max_length=1, null=True),
        ),
    ]
