# Generated by Django 5.2 on 2025-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_form99_swap_text_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='form3x',
            name='filing_frequency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form3x',
            name='report_type_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
