# Generated by Django 5.2 on 2025-05-20 19:59

from django.db import migrations
from django.db.models import Case, When, Value as V


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0015_form3x_filing_frequency_form3x_report_type_category"),
    ]

    operations = [
        # for reports made before we added the filing_frequency
        # and report_type_category fields
        migrations.RunSQL(
            """
        UPDATE reports_form3x f
        SET filing_frequency = CASE
            WHEN r.report_code IN (
                'M2', 'M3', 'M4', 'M5', 'M6', 'M7',
                'M8', 'M9', 'M10', 'M11', 'M12'
            ) THEN 'M'
            ELSE 'Q'
        END,
        report_type_category = CASE
            WHEN r.report_code IN (
                'M11', 'M12', 'MY'
            ) THEN 'Non-Election Year'
            ELSE 'Election Year'
        END
        FROM reports_report as r
        WHERE r.form_3x_id = f.id AND filing_frequency IS NULL AND report_type_category IS NULL;
    """,
            reverse_sql="",
        )
    ]
