# Generated by Django 5.2 on 2025-05-20 19:59

from django.db import migrations
from django.db.models import F, Case, When, Value as V


def determine_frequency_and_category(apps, schema_editor):
    # for reports made before we added the filing_frequency and report_type_category fields
    Form3X = apps.get_model("reports", "Form3X")
    Form3X.objects.filter(
        filing_frequency__isnull=True, report_type_category__isnull=True
    ).update(
        filing_frequency=Case(
            When(
                report__report_code__in=[
                    "M2",
                    "M3",
                    "M4",
                    "M5",
                    "M6",
                    "M7",
                    "M8",
                    "M9",
                    "M10",
                    "M11",
                    "M12",
                ],
                then=V("M"),
            ),
            default=V("Q"),
        ),
        report_type_category=Case(
            When(
                report__report_code__in=["M11", "M12", "MY"], then=V("Non-Election Year")
            ),
            default=V("Election Year"),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0015_form3x_filing_frequency_form3x_report_type_category"),
    ]

    operations = [
        migrations.RunSQL(
            """
        UPDATE reports_form3x f
        SET filing_frequency = CASE
            WHEN r.report_code IN (
                'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11', 'M12'
            ) THEN 'M'
            ELSE 'Q'
        END,
        report_type_category = CASE
            WHEN r.report_code IN (
                'M11', 'M12', 'MY'
            ) THEN 'Non-Election Year'
            ELSE 'Election Year'
        END
        FROM reports_report as r
        WHERE r.form_3x_id = f.id AND filing_frequency IS NULL AND report_type_category IS NULL;
    """,
            reverse_sql="",
        )
    ]
