# Generated by Django 5.2 on 2025-05-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0016_determine_frequency_and_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="form99",
            name="filing_frequency",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="form99",
            name="pdf_attachment",
            field=models.BooleanField(default=False),
        ),
    ]
