export const duplicatesResponse: any = {
  contacts: [
    {
      entity_id: 219,
      cmte_id: 'C00515064',
      transaction_id: '',
      duplicate_entity: 'IND20201026000436264,IND20201026000436263,IND20201026000436262',
      file_selected: '',
      user_selected_value: null,
      exsisting_db: null,
      file_name: 'how_to_data_IND_step2.csv',
      entity_type: 'IND',
      street_1: '101 South High St',
      street_2: '',
      city: 'Chicago',
      state: 'IL',
      zip_code: '82800',
      employer: 'Self Employeed',
      occupation: '',
      entity_name: '',
      last_name: 'Carter',
      first_name: 'Sally',
      middle_name: '',
      preffix: 'Mrs',
      suffix: '',
      contact_from: 'file',
      contacts_from_db: [
        {
          cmte_id: 'C00515064',
          entity_id: 'IND20201026000436264',
          entity_type: 'IND',
          entity_name: '',
          first_name: 'Sally',
          last_name: 'Carter',
          middle_name: '',
          prefix: 'Mrs.',
          suffix: '',
          street_1: '101 S High St',
          street_2: '',
          city: 'Chicago',
          state: 'IL',
          zip_code: '82800',
          occupation: '',
          employer: 'Self Employeed',
          cand_office: null,
          cand_office_state: null,
          cand_office_district: null,
          ref_cand_cmte_id: null,
          cand_election_year: null,
          phone_number: null,
          last_update_date: '2020-10-26T13:59:31.287632',
          user_selected_value: false
        },
        {
          cmte_id: 'C00515064',
          entity_id: 'IND20201026000436263',
          entity_type: 'IND',
          entity_name: '',
          first_name: 'Sally',
          last_name: 'Carter',
          middle_name: '',
          prefix: 'Mrs.',
          suffix: '',
          street_1: '101 S. High St.',
          street_2: '',
          city: 'Chicago',
          state: 'IL',
          zip_code: '82800',
          occupation: '',
          employer: 'Self Employeed',
          cand_office: null,
          cand_office_state: null,
          cand_office_district: null,
          ref_cand_cmte_id: null,
          cand_election_year: null,
          phone_number: null,
          last_update_date: '2020-10-26T13:59:31.287632',
          user_selected_value: false
        },
        {
          cmte_id: 'C00515064',
          entity_id: 'IND20201026000436262',
          entity_type: 'IND',
          entity_name: '',
          first_name: 'Sally',
          last_name: 'Carter',
          middle_name: '',
          prefix: '',
          suffix: '',
          street_1: '101 S. High St.',
          street_2: '',
          city: 'Chicago',
          state: 'IL',
          zip_code: '82800',
          occupation: '',
          employer: 'Self Employeed',
          cand_office: null,
          cand_office_state: null,
          cand_office_district: null,
          ref_cand_cmte_id: null,
          cand_election_year: null,
          phone_number: null,
          last_update_date: '2020-10-26T13:59:31.287632',
          user_selected_value: false
        }
      ],
      user_selected_option: ''
    },
    {
      entity_id: 220,
      cmte_id: 'C00515064',
      transaction_id: '',
      duplicate_entity: 'IND20201026000436268,IND20201026000436267,IND20201026000436266,IND20201026000436265',
      file_selected: '',
      user_selected_value: null,
      exsisting_db: null,
      file_name: 'how_to_data_IND_step2.csv',
      entity_type: 'IND',
      street_1: '200 Greenway Driv',
      street_2: '',
      city: 'Houston',
      state: 'TX',
      zip_code: '77023',
      employer: 'Filer',
      occupation: 'Triumph',
      entity_name: '',
      last_name: 'Smith',
      first_name: 'Larry',
      middle_name: '',
      preffix: '',
      suffix: '',
      contact_from: 'file',
      contacts_from_db: [
        {
          cmte_id: 'C00515064',
          entity_id: 'IND20201026000436268',
          entity_type: 'IND',
          entity_name: '',
          first_name: 'Larry',
          last_name: 'Smith',
          middle_name: '',
          prefix: '',
          suffix: '',
          street_1: '201 Greenway Dr.',
          street_2: '#1B',
          city: 'Houston',
          state: 'TX',
          zip_code: '77023',
          occupation: 'Triumph',
          employer: 'Filer',
          cand_office: null,
          cand_office_state: null,
          cand_office_district: null,
          ref_cand_cmte_id: null,
          cand_election_year: null,
          phone_number: null,
          last_update_date: '2020-10-26T13:59:31.287632',
          user_selected_value: false
        },
        {
          cmte_id: 'C00515064',
          entity_id: 'IND20201026000436267',
          entity_type: 'IND',
          entity_name: '',
          first_name: 'Larry',
          last_name: 'Smith',
          middle_name: '',
          prefix: '',
          suffix: '',
          street_1: '201 Greenway Dr.',
          street_2: '',
          city: 'Houston',
          state: 'TX',
          zip_code: '77023',
          occupation: 'Triumph',
          employer: 'Filer',
          cand_office: null,
          cand_office_state: null,
          cand_office_district: null,
          ref_cand_cmte_id: null,
          cand_election_year: null,
          phone_number: null,
          last_update_date: '2020-10-26T13:59:31.287632',
          user_selected_value: false
        },
        {
          cmte_id: 'C00515064',
          entity_id: 'IND20201026000436266',
          entity_type: 'IND',
          entity_name: '',
          first_name: 'Larry',
          last_name: 'Smith',
          middle_name: '',
          prefix: '',
          suffix: '',
          street_1: '201 Greenway Drive',
          street_2: '',
          city: 'Houston',
          state: 'TX',
          zip_code: '77023',
          occupation: 'Triumph',
          employer: 'Filer',
          cand_office: null,
          cand_office_state: null,
          cand_office_district: null,
          ref_cand_cmte_id: null,
          cand_election_year: null,
          phone_number: null,
          last_update_date: '2020-10-26T13:59:31.287632',
          user_selected_value: false
        },
        {
          cmte_id: 'C00515064',
          entity_id: 'IND20201026000436265',
          entity_type: 'IND',
          entity_name: '',
          first_name: 'Larry',
          last_name: 'Smith',
          middle_name: '',
          prefix: '',
          suffix: '',
          street_1: '200 Greenway Drive',
          street_2: '',
          city: 'Houston',
          state: 'TX',
          zip_code: '77023',
          occupation: 'Triumph',
          employer: 'Filer',
          cand_office: null,
          cand_office_state: null,
          cand_office_district: null,
          ref_cand_cmte_id: null,
          cand_election_year: null,
          phone_number: null,
          last_update_date: '2020-10-26T13:59:31.287632',
          user_selected_value: false
        }
      ],
      user_selected_option: ''
    }
  ],
  allDone: false,
  totalcontactsCount: 2,
  itemsPerPage: 4,
  pageNumber: 1,
  totalPages: 1
};
