# Generated by Django 3.2.11 on 2022-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f3x_summaries", "0002_f3xsummary_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="f3xsummary",
            name="L6a_year_for_above_ytd",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="city",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="committee_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="coverage_from_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="coverage_through_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="date_of_election",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="date_signed",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="election_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="filer_committee_id_number",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="form_type",
            field=models.CharField(
                choices=[("F3XT", "F3XT"), ("F3XN", "F3XN"), ("F3XA", "F3XA")],
                default="F3XN",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="report_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="state",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="state_of_election",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="street_1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="street_2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="treasurer_first_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="treasurer_last_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="treasurer_middle_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="treasurer_prefix",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="treasurer_suffix",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="f3xsummary",
            name="zip",
            field=models.TextField(blank=True, null=True),
        ),
    ]
