# Generated by Django 3.2.12 on 2022-04-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee_accounts', '0001_initial'),
        ('f3x_summaries', '0005_auto_20220405_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f3xsummary',
            name='committee_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee_accounts.committeeaccount'),
        ),
        migrations.AlterField(
            model_name='f3xsummary',
            name='date_signed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='f3xsummary',
            name='filer_committee_id_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='f3xsummary',
            name='form_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='f3xsummary',
            name='treasurer_first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='f3xsummary',
            name='treasurer_last_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
