# Generated by Django 3.2.12 on 2022-05-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f3x_summaries', '0007_add_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f3xsummary',
            name='change_of_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='f3xsummary',
            name='qualified_committee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL('UPDATE f3x_summaries SET change_of_address = NULL, qualified_committee = NULL;')
    ]
