# Generated by Django 3.2.12 on 2022-05-25 15:57

from django.db import migrations, models
from django.core import serializers
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    original_apps = serializers.python.apps
    serializers.python.apps = apps
    fixture_file = "fecfiler/f3x_summaries/fixtures/report_code_labels.json"
    try:
        with open(fixture_file) as fixture:
            objects = serializers.deserialize("json", fixture)
            for obj in objects:
                obj.save()
    except:
        print("fixture could not be read")
    serializers.python.apps = original_apps


class Migration(migrations.Migration):

    dependencies = [
        ("f3x_summaries", "0009_auto_20220515_2116"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCodeLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField(blank=True, null=True)),
                ("report_code", models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                "db_table": "report_code_labels",
            },
        ),
        migrations.AddIndex(
            model_name="reportcodelabel",
            index=models.Index(
                fields=["report_code"], name="report_code_report__9cd13b_idx"
            ),
        ),
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name="f3xsummary",
            name="report_code",
            field=models.ForeignKey(
                blank=True,
                db_column="report_code",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="f3x_summaries.reportcodelabel",
                to_field="report_code",
            ),
        ),
    ]
