# Generated by Django 3.2.12 on 2022-05-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f3x_summaries', '0009_auto_20220515_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCodeLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('report_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_code_labels',
            },
        ),
        migrations.AddIndex(
            model_name='reportcodelabel',
            index=models.Index(fields=['report_code'], name='report_code_report__9cd13b_idx'),
        ),
    ]
