# Generated by Django 3.2.12 on 2022-08-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0005_auto_20220811_1213'),
        ('f3x_summaries', '0014_patch_report_code_label_MY_20220808_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='f3xsummary',
            name='upload_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_services.uploadsubmission'),
        ),
    ]
