# Generated by Django 3.2.12 on 2022-09-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f3x_summaries', '0016_f3xsummary_webprint_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='f3xsummary',
            name='calculation_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
