# Generated by Django 3.2.12 on 2022-09-09 16:41

from django.db import migrations, models


def update_uuid(apps, schema_editor):
    F3XSummary = apps.get_model("f3x_summaries", "F3XSummary")  # noqa
    UploadSubmission = apps.get_model("web_services", "UploadSubmission")  # noqa
    WebPrintSubmission = apps.get_model("web_services", "WebPrintSubmission")  # noqa
    upload_uuid = UploadSubmission.objects.filter(
        id=models.OuterRef("upload_submission_old")
    ).values_list("uuid")[:1]
    webprint_uuid = WebPrintSubmission.objects.filter(
        id=models.OuterRef("webprint_submission_old")
    ).values_list("uuid")[:1]
    F3XSummary.objects.update(
        upload_submission=models.Subquery(upload_uuid),
        webprint_submission=models.Subquery(webprint_uuid),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("web_services", "0012_use_uuid"),
        ("f3x_summaries", "0019_f3xsummary_submission_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="f3xsummary",
            name="upload_submission",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.SET_NULL,
                to="web_services.UploadSubmission",
            ),
        ),
        migrations.AddField(
            model_name="f3xsummary",
            name="webprint_submission",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.SET_NULL,
                to="web_services.WebPrintSubmission",
            ),
        ),
        migrations.RunPython(update_uuid),
        migrations.RemoveField(
            model_name="f3xsummary",
            name="upload_submission_old",
        ),
        migrations.RemoveField(
            model_name="f3xsummary",
            name="webprint_submission_old",
        ),
    ]
