# Generated by Django 3.2.12 on 2022-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    def update_uuid(apps, schema_editor):
        F3XSummary = apps.get_model("web_services", "F3XSummary")
        UploadSubmission = apps.get_model("web_services", "UploadSubmission")
        WebPrintSubmission = apps.get_model("web_services", "WebPrintSubmission")
        upload_uuid = UploadSubmission.objects.filter(
            id=models.OuterRef("upload_submission_old")
        ).values_list("uuid")[:1]
        webprint_uuid = WebPrintSubmission.objects.filter(
            id=models.OuterRef("webprint_submission_old")
        ).values_list("uuid")[:1]
        F3XSummary.objects.update(
            upload_submission=models.Subquery(upload_uuid),
            webprint_submission=models.Subquery(webprint_uuid),
        )

    dependencies = [
        ("web_services", "0012_use_uuid"),
        ("f3x_summaries", "0017_f3xsummary_calculation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="f3xsummary",
            name="upload_submission",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.SET_NULL,
                to="web_services.dotfec",
            ),
        ),
        migrations.AddField(
            model_name="f3xsummary",
            name="webprint_submission",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.SET_NULL,
                to="web_services.dotfec",
            ),
        ),
        migrations.RunPython(update_uuid),
        migrations.RemoveField(
            model_name="f3xsummary",
            name="upload_submission_old",
        ),
        migrations.RemoveField(
            model_name="f3xsummary",
            name="webprint_submission_old",
        ),
    ]
