# Generated by Django 3.2.12 on 2022-09-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memo_text", "0004_report_fk"),
        ("f3x_summaries", "0021_f3xsummary_uuid_primary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="f3xsummary",
            name="id",
        ),
    ]
