# Generated by Django 3.2.12 on 2022-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    def update_uuid(apps, schema_editor):
        F3XSummary = apps.get_model("f3x_summaries", "F3XSummary")
        CommitteeAccount = apps.get_model("committee_accounts", "CommitteeAccount")
        committee_uuid = CommitteeAccount.objects.filter(
            id=models.OuterRef("committee_account_old")
        ).values_list("uuid")[:1]
        F3XSummary.objects.update(committee_account=models.Subquery(committee_uuid))

    dependencies = [
        ("f3x_summaries", "0023_committee_fk_to_int"),
        ("committee_accounts", "0003_uuid_pk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="f3xsummary",
            old_name="committee_account",
            new_name="committee_account_old",
        ),
        migrations.AddField(
            model_name="f3xsummary",
            name="committee_account",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.CASCADE,
                to="committee_accounts.CommitteeAccount",
            ),
        ),
        migrations.RunPython(update_uuid),
        migrations.RemoveField(
            model_name="f3xsummary",
            name="committee_account_old",
        ),
    ]
