# Generated by Django 3.2.12 on 2022-09-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0014_auto_20220915_1309'),
        ('f3x_summaries', '0024_committee_uuid_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f3xsummary',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='f3xsummary',
            name='upload_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_services.uploadsubmission'),
        ),
        migrations.AlterField(
            model_name='f3xsummary',
            name='webprint_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_services.webprintsubmission'),
        ),
    ]
