# Generated by Django 4.1.3 on 2023-04-27 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("f3x_summaries", "0026_auto_20221130_1459"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="f3xsummary",
            name="filer_committee_id_number",
        ),
    ]
