# Generated by Django 4.1.3 on 2023-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f3x_summaries', '0027_remove_f3xsummary_filer_committee_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='f3xsummary',
            name='report_version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
